"""Registered navigation. The default main order is a product decision:

Overview, Customers / CRM, Catalog, PI, Inventory, Sales, Quotes, Orders, Billing,
Finance, HR, Reports. Sort orders are spaced by 10 so a future module can be inserted
(e.g. Subscriptions at 130) without renumbering existing entries.
"""

from app.modules.navigation.registry import NavDefinition, NavigationRegistry


def build_registry() -> NavigationRegistry:
    registry = NavigationRegistry()
    main = [
        NavDefinition(
            "overview",
            "Overview",
            "/",
            "layout-dashboard",
            "main",
            10,
            required_permissions=("overview.read",),
            analytics_id="nav.overview",
            keywords=("dashboard", "home"),
        ),
        NavDefinition(
            "customers",
            "Customers / CRM",
            "/customers",
            "users",
            "main",
            20,
            required_permissions=("customers.read",),
            analytics_id="nav.customers",
            keywords=("crm", "contacts", "clients"),
        ),
        NavDefinition(
            "catalog",
            "Catalog",
            "/catalog",
            "package",
            "main",
            30,
            required_permissions=("catalog.read",),
            analytics_id="nav.catalog",
            keywords=("services", "offerings", "packages", "products", "pricing"),
        ),
        NavDefinition(
            "pi",
            "PI",
            "/pi",
            "bot",
            "main",
            40,
            type="product",
            required_permissions=("pi.read",),
            required_product="pi",
            badge="pi.open_handoffs",
            analytics_id="nav.pi",
            keywords=("whatsapp", "assistant", "ai", "inbox"),
            description="AI WhatsApp customer assistant",
        ),
        NavDefinition(
            "inventory",
            "Inventory",
            "/inventory",
            "warehouse",
            "main",
            50,
            required_permissions=("inventory.read",),
            analytics_id="nav.inventory",
            keywords=("stock", "warehouse"),
        ),
        NavDefinition(
            "sales",
            "Sales",
            "/sales",
            "trending-up",
            "main",
            60,
            required_permissions=("sales.read",),
            analytics_id="nav.sales",
            keywords=("leads", "pipeline", "opportunities"),
        ),
        NavDefinition(
            "quotes",
            "Quotes",
            "/quotes",
            "file-text",
            "main",
            70,
            required_permissions=("quotes.read",),
            analytics_id="nav.quotes",
            keywords=("estimates", "proposals"),
        ),
        NavDefinition(
            "orders",
            "Orders",
            "/orders",
            "shopping-cart",
            "main",
            80,
            required_permissions=("orders.read",),
            analytics_id="nav.orders",
        ),
        NavDefinition(
            "billing",
            "Billing",
            "/billing",
            "receipt",
            "main",
            90,
            required_permissions=("billing.read",),
            analytics_id="nav.billing",
            keywords=("invoices", "payments"),
        ),
        NavDefinition(
            "finance",
            "Finance",
            "/finance",
            "landmark",
            "main",
            100,
            required_permissions=("finance.read",),
            analytics_id="nav.finance",
            keywords=("expenses", "cash", "receivables"),
        ),
        NavDefinition(
            "hr",
            "HR",
            "/hr",
            "id-card",
            "main",
            110,
            required_permissions=("hr.read",),
            analytics_id="nav.hr",
            keywords=("employees", "people", "staff"),
        ),
        NavDefinition(
            "reports",
            "Reports",
            "/reports",
            "chart-column",
            "main",
            120,
            required_permissions=("reports.read",),
            analytics_id="nav.reports",
            keywords=("analytics", "revenue"),
        ),
    ]
    admin = [
        NavDefinition(
            "settings",
            "Settings",
            "/settings",
            "settings",
            "admin",
            10,
            required_permissions=("settings.manage",),
            analytics_id="nav.settings",
        ),
        NavDefinition(
            "members",
            "Users / Members",
            "/settings/members",
            "user-cog",
            "admin",
            20,
            required_permissions=("admin.members.read",),
            analytics_id="nav.members",
        ),
        NavDefinition(
            "roles",
            "Roles & Permissions",
            "/settings/roles",
            "shield-check",
            "admin",
            30,
            required_permissions=("admin.members.read",),
            analytics_id="nav.roles",
        ),
        NavDefinition(
            "branches",
            "Branches",
            "/settings/branches",
            "building-2",
            "admin",
            40,
            required_permissions=("admin.organization.manage",),
            analytics_id="nav.branches",
        ),
        NavDefinition(
            "departments",
            "Departments",
            "/settings/departments",
            "network",
            "admin",
            50,
            required_permissions=("admin.organization.manage",),
            analytics_id="nav.departments",
        ),
        NavDefinition(
            "environments",
            "Environments",
            "/settings/environments",
            "layers",
            "admin",
            60,
            required_permissions=("admin.environments.manage",),
            analytics_id="nav.environments",
        ),
        NavDefinition(
            "integrations",
            "Integrations",
            "/settings/integrations",
            "plug",
            "admin",
            65,
            required_permissions=("integrations.read",),
            analytics_id="nav.integrations",
            keywords=("connections", "webhooks", "oauth", "sync", "api keys"),
        ),
        NavDefinition(
            "audit",
            "Audit Logs",
            "/settings/audit",
            "scroll-text",
            "admin",
            70,
            required_permissions=("audit.read",),
            analytics_id="nav.audit",
        ),
        NavDefinition(
            "products",
            "Platform Products",
            "/settings/products",
            "blocks",
            "admin",
            80,
            required_permissions=("admin.products.manage",),
            analytics_id="nav.products",
        ),
        NavDefinition(
            "notifications",
            "Notifications",
            "/notifications",
            "bell",
            "admin",
            90,
            required_permissions=("notifications.read",),
            badge="notifications.unread",
            analytics_id="nav.notifications",
        ),
    ]
    pi_children = [
        NavDefinition(
            "pi-overview",
            "PI Overview",
            "/pi",
            "gauge",
            "main",
            10,
            type="page",
            parent="pi",
            required_permissions=("pi.read",),
            analytics_id="nav.pi.overview",
        ),
        NavDefinition(
            "pi-inbox",
            "Inbox",
            "/pi/inbox",
            "inbox",
            "main",
            20,
            type="page",
            parent="pi",
            required_permissions=("pi.read",),
            analytics_id="nav.pi.inbox",
            keywords=("conversations", "messages"),
        ),
        NavDefinition(
            "pi-agents",
            "Agents",
            "/pi/agents",
            "workflow",
            "main",
            30,
            type="page",
            parent="pi",
            required_permissions=("pi.agents.manage",),
            analytics_id="nav.pi.agents",
        ),
        NavDefinition(
            "pi-whatsapp",
            "WhatsApp",
            "/pi/whatsapp",
            "message-circle",
            "main",
            40,
            type="page",
            parent="pi",
            required_permissions=("pi.whatsapp.manage",),
            analytics_id="nav.pi.whatsapp",
        ),
        NavDefinition(
            "pi-knowledge",
            "Knowledge",
            "/pi/knowledge",
            "book-open",
            "main",
            50,
            type="page",
            parent="pi",
            required_permissions=("pi.knowledge.manage",),
            required_feature="knowledge",
            required_product="pi",
            analytics_id="nav.pi.knowledge",
        ),
        NavDefinition(
            "pi-handoffs",
            "Handoffs",
            "/pi/handoffs",
            "life-buoy",
            "main",
            60,
            type="page",
            parent="pi",
            any_permissions=("pi.handoffs.manage", "pi.inbox.reply"),
            required_feature="handoff",
            required_product="pi",
            badge="pi.open_handoffs",
            analytics_id="nav.pi.handoffs",
        ),
        NavDefinition(
            "pi-analytics",
            "Analytics",
            "/pi/analytics",
            "chart-line",
            "main",
            70,
            type="page",
            parent="pi",
            required_permissions=("pi.analytics.read",),
            analytics_id="nav.pi.analytics",
        ),
        NavDefinition(
            "pi-settings",
            "Settings",
            "/pi/settings",
            "sliders-horizontal",
            "main",
            80,
            type="page",
            parent="pi",
            required_permissions=("pi.settings.manage",),
            analytics_id="nav.pi.settings",
        ),
    ]
    integration_children = [
        NavDefinition(
            f"integrations-{key}",
            label,
            route,
            icon,
            "admin",
            order,
            type="page",
            parent="integrations",
            required_permissions=(permission,),
            analytics_id=f"nav.integrations.{key}",
        )
        for key, label, route, icon, order, permission in [
            ("catalog", "Directory", "/settings/integrations", "plug", 10, "integrations.read"),
            (
                "webhooks",
                "Outbound webhooks",
                "/settings/integrations/webhooks",
                "send",
                20,
                "integrations.read",
            ),
            (
                "events",
                "Inbound events",
                "/settings/integrations/events",
                "inbox",
                30,
                "integrations.read",
            ),
            (
                "jobs",
                "Sync jobs",
                "/settings/integrations/jobs",
                "refresh-cw",
                40,
                "integrations.read",
            ),
            (
                "failures",
                "Failures",
                "/settings/integrations/failures",
                "triangle-alert",
                50,
                "integrations.read",
            ),
            (
                "health",
                "Health",
                "/settings/integrations/health",
                "activity",
                60,
                "integrations.read",
            ),
            (
                "api-keys",
                "API keys",
                "/settings/integrations/api-keys",
                "key-round",
                70,
                "api_keys.manage",
            ),
        ]
    ]
    for item in [*main, *admin, *pi_children, *integration_children, *module_pages()]:
        registry.register(item)
    return registry


def page(
    parent: str,
    key: str,
    label: str,
    route: str,
    icon: str,
    order: int,
    *permissions: str,
    product: str | None = None,
) -> NavDefinition:
    """A workspace page inside a module (rendered as module tabs and in search)."""
    return NavDefinition(
        f"{parent}-{key}",
        label,
        route,
        icon,
        "main",
        order,
        type="page",
        parent=parent,
        required_permissions=permissions,
        required_product=product,
        analytics_id=f"nav.{parent}.{key}",
    )


def module_pages() -> list[NavDefinition]:
    return [
        page("customers", "list", "Customers", "/customers", "users", 10, "customers.read"),
        page(
            "customers", "segments", "Segments", "/customers/segments", "tags", 20, "customers.read"
        ),
        page("catalog", "overview", "Overview", "/catalog", "gauge", 10, "catalog.read"),
        page(
            "catalog",
            "products",
            "Services & offerings",
            "/catalog/products",
            "package",
            20,
            "catalog.read",
        ),
        page(
            "catalog",
            "categories",
            "Categories",
            "/catalog/categories",
            "folder-tree",
            30,
            "catalog.read",
        ),
        page(
            "catalog",
            "pricing",
            "Pricing",
            "/catalog/pricing",
            "badge-dollar-sign",
            40,
            "catalog.read",
        ),
        page("inventory", "overview", "Overview", "/inventory", "gauge", 10, "inventory.read"),
        page("inventory", "stock", "Stock", "/inventory/stock", "boxes", 20, "inventory.read"),
        page(
            "inventory",
            "locations",
            "Locations",
            "/inventory/locations",
            "map-pin",
            30,
            "inventory.read",
        ),
        page(
            "inventory",
            "movements",
            "Movements",
            "/inventory/movements",
            "arrow-left-right",
            40,
            "inventory.read",
        ),
        page("sales", "overview", "Overview", "/sales", "gauge", 10, "sales.read"),
        page("sales", "pipeline", "Pipeline", "/sales/pipeline", "kanban", 20, "sales.read"),
        page("sales", "leads", "Leads", "/sales/leads", "target", 30, "sales.read"),
        page("quotes", "list", "Quotes", "/quotes", "file-text", 10, "quotes.read"),
        page(
            "quotes", "approvals", "Approvals", "/quotes/approvals", "stamp", 20, "quotes.approve"
        ),
        page("orders", "list", "Orders", "/orders", "shopping-cart", 10, "orders.read"),
        page(
            "orders",
            "fulfillment",
            "Fulfillment",
            "/orders/fulfillment",
            "truck",
            20,
            "orders.read",
        ),
        page("billing", "overview", "Overview", "/billing", "gauge", 10, "billing.read"),
        page("billing", "invoices", "Invoices", "/billing/invoices", "receipt", 20, "billing.read"),
        page("billing", "payments", "Payments", "/billing/payments", "wallet", 30, "billing.read"),
        page("finance", "overview", "Overview", "/finance", "gauge", 10, "finance.read"),
        page(
            "finance",
            "receivables",
            "Receivables",
            "/finance/receivables",
            "hourglass",
            20,
            "finance.read",
        ),
        page(
            "finance",
            "expenses",
            "Expenses",
            "/finance/expenses",
            "credit-card",
            30,
            "finance.read",
        ),
        page("hr", "overview", "Overview", "/hr", "gauge", 10, "hr.read"),
        page("hr", "employees", "Employees", "/hr/employees", "users", 20, "hr.read"),
        page("hr", "departments", "Departments", "/hr/departments", "network", 30, "hr.read"),
        page("reports", "overview", "Overview", "/reports", "gauge", 10, "reports.read"),
        page(
            "reports",
            "revenue",
            "Revenue",
            "/reports/revenue",
            "trending-up",
            20,
            "reports.read",
            "billing.read",
        ),
        page(
            "reports",
            "customers",
            "Customers",
            "/reports/customers",
            "users",
            30,
            "reports.read",
            "customers.read",
        ),
        page(
            "reports",
            "orders",
            "Orders",
            "/reports/orders",
            "shopping-cart",
            40,
            "reports.read",
            "orders.read",
        ),
        page(
            "reports",
            "inventory",
            "Inventory",
            "/reports/inventory",
            "warehouse",
            50,
            "reports.read",
            "inventory.read",
        ),
        page(
            "reports",
            "quotes",
            "Quotes",
            "/reports/quotes",
            "file-text",
            60,
            "reports.read",
            "quotes.read",
        ),
        page(
            "reports",
            "billing",
            "Billing",
            "/reports/billing",
            "receipt",
            70,
            "reports.read",
            "billing.read",
        ),
        page(
            "reports",
            "employees",
            "Employees",
            "/reports/employees",
            "id-card",
            80,
            "reports.read",
            "hr.read",
        ),
        page(
            "reports",
            "pi",
            "PI Analytics",
            "/reports/pi",
            "bot",
            90,
            "reports.read",
            "pi.analytics.read",
            product="pi",
        ),
    ]


REGISTRY = build_registry()
