"""Integration platform: connections, inbound events, outbox, deliveries, sync, API keys.

Revision ID: 0004_integration_platform
Revises: ea6781564d8a

Generated with Alembic autogenerate and reviewed by hand: every table is environment
scoped (composite FK to environments(tenant_id, id)) and child tables reference their
parents through (tenant_id, environment_id, id). Idempotency is enforced by unique
constraints (inbound (connection_id, provider_event_id); deliveries (subscription_id,
outbox_event_id); one active sync job per connection+entity; globally unique API key
prefix and webhook endpoint token hash).

Data: grants the new integrations.* and api_keys.manage permissions to the existing
system owner/admin roles of every tenant (new tenants get them from SYSTEM_ROLES). The
downgrade drops the tables but leaves those role_permissions rows (harmless unknown
permissions for older code; re-upgrading is idempotent).
"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision = "0004_integration_platform"
down_revision = "ea6781564d8a"
branch_labels = None
depends_on = None

NEW_PERMISSIONS = (
    "integrations.read",
    "integrations.manage",
    "integrations.operate",
    "api_keys.manage",
)
BACKFILL = sa.text(
    "INSERT INTO role_permissions (id, tenant_id, role_id, permission) "
    "SELECT gen_random_uuid(), r.tenant_id, r.id, p.permission FROM roles r "
    "CROSS JOIN (VALUES " + ", ".join(f"('{p}')" for p in NEW_PERMISSIONS) + ") AS p(permission) "
    "WHERE r.is_system AND r.key IN ('owner', 'admin') "
    "ON CONFLICT ON CONSTRAINT uq_role_permissions_entry DO NOTHING"
)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "api_keys",
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("prefix", sa.String(length=40), nullable=False),
        sa.Column("secret_hash", sa.String(length=64), nullable=False),
        sa.Column(
            "scopes", postgresql.ARRAY(sa.String(length=60)), server_default="{}", nullable=False
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("created_by_membership_id", sa.Uuid(), nullable=True),
        sa.Column("created_by_name", sa.String(length=160), server_default="", nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("environment_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("length(btrim(name)) > 0", name=op.f("ck_api_keys_name_nonempty")),
        sa.ForeignKeyConstraint(
            ["tenant_id", "environment_id"],
            ["environments.tenant_id", "environments.id"],
            name="fk_api_keys_environment",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_api_keys_tenant_id_tenants"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_api_keys")),
        sa.UniqueConstraint("prefix", name="uq_api_keys_prefix"),
        sa.UniqueConstraint("tenant_id", "environment_id", "id", name="uq_api_keys_scope_id"),
    )
    op.create_index(
        "ix_api_keys_scope", "api_keys", ["tenant_id", "environment_id", "created_at"], unique=False
    )
    op.create_table(
        "integration_connections",
        sa.Column("integration_key", sa.String(length=60), nullable=False),
        sa.Column("display_name", sa.String(length=120), nullable=False),
        sa.Column("mode", sa.String(length=16), nullable=False),
        sa.Column("status", sa.String(length=16), server_default="draft", nullable=False),
        sa.Column(
            "config", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False
        ),
        sa.Column("credentials_encrypted", sa.Text(), nullable=True),
        sa.Column(
            "credential_hints",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
        ),
        sa.Column(
            "scopes", postgresql.ARRAY(sa.String(length=200)), server_default="{}", nullable=False
        ),
        sa.Column("sync_direction", sa.String(length=16), server_default="none", nullable=False),
        sa.Column("health", sa.String(length=16), server_default="unknown", nullable=False),
        sa.Column("circuit_state", sa.String(length=16), server_default="closed", nullable=False),
        sa.Column("circuit_failure_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("circuit_opened_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("consecutive_failures", sa.Integer(), server_default="0", nullable=False),
        sa.Column("last_success_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_failure_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_error", sa.String(length=300), nullable=True),
        sa.Column("last_error_code", sa.String(length=64), nullable=True),
        sa.Column("last_health_check_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_latency_ms", sa.Integer(), nullable=True),
        sa.Column("rate_limited_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("connected_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("disabled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("webhook_token_hash", sa.String(length=64), nullable=True),
        sa.Column("created_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("environment_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "circuit_state IN ('closed', 'open', 'half_open')",
            name=op.f("ck_integration_connections_circuit_state"),
        ),
        sa.CheckConstraint(
            "health IN ('healthy', 'degraded', 'failing', 'unknown')",
            name=op.f("ck_integration_connections_health"),
        ),
        sa.CheckConstraint(
            "mode IN ('sandbox', 'production')", name=op.f("ck_integration_connections_mode")
        ),
        sa.CheckConstraint(
            "status IN ('draft', 'connecting', 'connected', 'degraded', 'expired', 'revoked', 'disabled', 'error')",
            name=op.f("ck_integration_connections_status"),
        ),
        sa.CheckConstraint(
            "sync_direction IN ('none', 'pull', 'push', 'bidirectional')",
            name=op.f("ck_integration_connections_sync_direction"),
        ),
        sa.CheckConstraint(
            "length(btrim(display_name)) > 0",
            name=op.f("ck_integration_connections_display_name_nonempty"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "environment_id"],
            ["environments.tenant_id", "environments.id"],
            name="fk_integration_connections_environment",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_integration_connections_tenant_id_tenants"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_integration_connections")),
        sa.UniqueConstraint(
            "tenant_id", "environment_id", "id", name="uq_integration_connections_scope_id"
        ),
    )
    op.create_index(
        "ix_integration_connections_scope_key",
        "integration_connections",
        ["tenant_id", "environment_id", "integration_key"],
        unique=False,
    )
    op.create_index(
        "uq_integration_connections_webhook_token",
        "integration_connections",
        ["webhook_token_hash"],
        unique=True,
        postgresql_where=sa.text("webhook_token_hash IS NOT NULL"),
    )
    op.create_table(
        "integration_webhook_subscriptions",
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("url", sa.String(length=2048), nullable=False),
        sa.Column(
            "event_types",
            postgresql.ARRAY(sa.String(length=80)),
            server_default="{}",
            nullable=False,
        ),
        sa.Column("enabled", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("secret_encrypted", sa.Text(), nullable=False),
        sa.Column("secret_hint", sa.String(length=8), nullable=False),
        sa.Column("last_delivery_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_delivery_status", sa.String(length=16), nullable=True),
        sa.Column("failure_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("environment_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "length(btrim(name)) > 0",
            name=op.f("ck_integration_webhook_subscriptions_name_nonempty"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "environment_id"],
            ["environments.tenant_id", "environments.id"],
            name="fk_integration_webhook_subscriptions_environment",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_integration_webhook_subscriptions_tenant_id_tenants"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_integration_webhook_subscriptions")),
        sa.UniqueConstraint(
            "tenant_id",
            "environment_id",
            "id",
            name="uq_integration_webhook_subscriptions_scope_id",
        ),
    )
    op.create_index(
        "ix_integration_webhook_subscriptions_scope",
        "integration_webhook_subscriptions",
        ["tenant_id", "environment_id", "enabled"],
        unique=False,
    )
    op.create_table(
        "outbox_events",
        sa.Column("event_type", sa.String(length=80), nullable=False),
        sa.Column(
            "payload", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False
        ),
        sa.Column("entity_type", sa.String(length=60), nullable=True),
        sa.Column("entity_id", sa.Uuid(), nullable=True),
        sa.Column("status", sa.String(length=16), server_default="pending", nullable=False),
        sa.Column("attempts", sa.Integer(), server_default="0", nullable=False),
        sa.Column("available_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("dispatched_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("correlation_id", sa.String(length=64), nullable=True),
        sa.Column("origin", sa.String(length=80), nullable=True),
        sa.Column("fingerprint", sa.String(length=64), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("environment_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('pending', 'dispatched', 'failed')", name=op.f("ck_outbox_events_status")
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "environment_id"],
            ["environments.tenant_id", "environments.id"],
            name="fk_outbox_events_environment",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_outbox_events_tenant_id_tenants"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_outbox_events")),
        sa.UniqueConstraint("tenant_id", "environment_id", "id", name="uq_outbox_events_scope_id"),
    )
    op.create_index(
        "ix_outbox_events_pending", "outbox_events", ["status", "available_at"], unique=False
    )
    op.create_index(
        "ix_outbox_events_scope_created",
        "outbox_events",
        ["tenant_id", "environment_id", "created_at"],
        unique=False,
    )
    op.create_table(
        "integration_activities",
        sa.Column("connection_id", sa.Uuid(), nullable=False),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("outcome", sa.String(length=16), nullable=False),
        sa.Column("message", sa.String(length=300), nullable=False),
        sa.Column("latency_ms", sa.Integer(), nullable=True),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("environment_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "outcome IN ('success', 'failure', 'info')",
            name=op.f("ck_integration_activities_outcome"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "environment_id", "connection_id"],
            [
                "integration_connections.tenant_id",
                "integration_connections.environment_id",
                "integration_connections.id",
            ],
            name="fk_integration_activities_connection_id",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "environment_id"],
            ["environments.tenant_id", "environments.id"],
            name="fk_integration_activities_environment",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_integration_activities_tenant_id_tenants"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_integration_activities")),
        sa.UniqueConstraint(
            "tenant_id", "environment_id", "id", name="uq_integration_activities_scope_id"
        ),
    )
    op.create_index(
        "ix_integration_activities_connection",
        "integration_activities",
        ["tenant_id", "environment_id", "connection_id", "created_at"],
        unique=False,
    )
    op.create_table(
        "integration_deliveries",
        sa.Column("subscription_id", sa.Uuid(), nullable=False),
        sa.Column("outbox_event_id", sa.Uuid(), nullable=False),
        sa.Column("event_type", sa.String(length=80), nullable=False),
        sa.Column("status", sa.String(length=16), server_default="pending", nullable=False),
        sa.Column("attempt_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("max_attempts", sa.Integer(), server_default="8", nullable=False),
        sa.Column("response_status", sa.Integer(), nullable=True),
        sa.Column("last_error", sa.String(length=300), nullable=True),
        sa.Column("next_attempt_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("delivered_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("idempotency_key", sa.String(length=120), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("environment_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('pending', 'running', 'succeeded', 'failed', 'dead_letter', 'cancelled', 'paused')",
            name=op.f("ck_integration_deliveries_status"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "environment_id", "outbox_event_id"],
            ["outbox_events.tenant_id", "outbox_events.environment_id", "outbox_events.id"],
            name="fk_integration_deliveries_outbox_event_id",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "environment_id", "subscription_id"],
            [
                "integration_webhook_subscriptions.tenant_id",
                "integration_webhook_subscriptions.environment_id",
                "integration_webhook_subscriptions.id",
            ],
            name="fk_integration_deliveries_subscription_id",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "environment_id"],
            ["environments.tenant_id", "environments.id"],
            name="fk_integration_deliveries_environment",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_integration_deliveries_tenant_id_tenants"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_integration_deliveries")),
        sa.UniqueConstraint(
            "subscription_id", "outbox_event_id", name="uq_integration_deliveries_event"
        ),
        sa.UniqueConstraint(
            "tenant_id", "environment_id", "id", name="uq_integration_deliveries_scope_id"
        ),
    )
    op.create_index(
        "ix_integration_deliveries_due",
        "integration_deliveries",
        ["status", "next_attempt_at"],
        unique=False,
    )
    op.create_index(
        "ix_integration_deliveries_subscription",
        "integration_deliveries",
        ["tenant_id", "environment_id", "subscription_id", "created_at"],
        unique=False,
    )
    op.create_table(
        "integration_external_refs",
        sa.Column("connection_id", sa.Uuid(), nullable=False),
        sa.Column("entity", sa.String(length=40), nullable=False),
        sa.Column("external_id", sa.String(length=200), nullable=False),
        sa.Column("platform_entity_id", sa.Uuid(), nullable=True),
        sa.Column("fingerprint", sa.String(length=64), nullable=False),
        sa.Column("last_write_origin", sa.String(length=16), nullable=False),
        sa.Column("last_synced_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("environment_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "last_write_origin IN ('provider', 'platform')",
            name=op.f("ck_integration_external_refs_origin"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "environment_id", "connection_id"],
            [
                "integration_connections.tenant_id",
                "integration_connections.environment_id",
                "integration_connections.id",
            ],
            name="fk_integration_external_refs_connection_id",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "environment_id"],
            ["environments.tenant_id", "environments.id"],
            name="fk_integration_external_refs_environment",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_integration_external_refs_tenant_id_tenants"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_integration_external_refs")),
        sa.UniqueConstraint(
            "connection_id", "entity", "external_id", name="uq_integration_external_refs_external"
        ),
        sa.UniqueConstraint(
            "tenant_id", "environment_id", "id", name="uq_integration_external_refs_scope_id"
        ),
    )
    op.create_table(
        "integration_inbound_events",
        sa.Column("connection_id", sa.Uuid(), nullable=False),
        sa.Column("integration_key", sa.String(length=60), nullable=False),
        sa.Column("provider_event_id", sa.String(length=200), nullable=False),
        sa.Column("event_type", sa.String(length=100), nullable=False),
        sa.Column("status", sa.String(length=16), server_default="received", nullable=False),
        sa.Column("signature_verified", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("payload_hash", sa.String(length=64), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("payload_truncated", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("attempt_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("received_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("processed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("next_attempt_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error_code", sa.String(length=64), nullable=True),
        sa.Column("correlation_id", sa.String(length=64), nullable=True),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("environment_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('received', 'queued', 'processing', 'processed', 'ignored', 'failed', 'dead_letter')",
            name=op.f("ck_integration_inbound_events_status"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "environment_id", "connection_id"],
            [
                "integration_connections.tenant_id",
                "integration_connections.environment_id",
                "integration_connections.id",
            ],
            name="fk_integration_inbound_events_connection_id",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "environment_id"],
            ["environments.tenant_id", "environments.id"],
            name="fk_integration_inbound_events_environment",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_integration_inbound_events_tenant_id_tenants"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_integration_inbound_events")),
        sa.UniqueConstraint(
            "connection_id",
            "provider_event_id",
            name="uq_integration_inbound_events_provider_event",
        ),
        sa.UniqueConstraint(
            "tenant_id", "environment_id", "id", name="uq_integration_inbound_events_scope_id"
        ),
    )
    op.create_index(
        "ix_integration_inbound_events_received",
        "integration_inbound_events",
        ["received_at"],
        unique=False,
    )
    op.create_index(
        "ix_integration_inbound_events_scope_status",
        "integration_inbound_events",
        ["tenant_id", "environment_id", "status", "received_at"],
        unique=False,
    )
    op.create_table(
        "integration_oauth_states",
        sa.Column("connection_id", sa.Uuid(), nullable=False),
        sa.Column("state_hash", sa.String(length=64), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("code_verifier_encrypted", sa.Text(), nullable=True),
        sa.Column("redirect_uri", sa.String(length=500), nullable=False),
        sa.Column(
            "scopes", postgresql.ARRAY(sa.String(length=200)), server_default="{}", nullable=False
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("consumed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("environment_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "environment_id", "connection_id"],
            [
                "integration_connections.tenant_id",
                "integration_connections.environment_id",
                "integration_connections.id",
            ],
            name="fk_integration_oauth_states_connection_id",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "environment_id"],
            ["environments.tenant_id", "environments.id"],
            name="fk_integration_oauth_states_environment",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_integration_oauth_states_tenant_id_tenants"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_integration_oauth_states")),
        sa.UniqueConstraint("state_hash", name="uq_integration_oauth_states_state_hash"),
        sa.UniqueConstraint(
            "tenant_id", "environment_id", "id", name="uq_integration_oauth_states_scope_id"
        ),
    )
    op.create_table(
        "integration_sync_cursors",
        sa.Column("connection_id", sa.Uuid(), nullable=False),
        sa.Column("entity", sa.String(length=40), nullable=False),
        sa.Column("cursor", sa.String(length=200), nullable=True),
        sa.Column("last_success_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("environment_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "environment_id", "connection_id"],
            [
                "integration_connections.tenant_id",
                "integration_connections.environment_id",
                "integration_connections.id",
            ],
            name="fk_integration_sync_cursors_connection_id",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "environment_id"],
            ["environments.tenant_id", "environments.id"],
            name="fk_integration_sync_cursors_environment",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_integration_sync_cursors_tenant_id_tenants"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_integration_sync_cursors")),
        sa.UniqueConstraint("connection_id", "entity", name="uq_integration_sync_cursors_entity"),
        sa.UniqueConstraint(
            "tenant_id", "environment_id", "id", name="uq_integration_sync_cursors_scope_id"
        ),
    )
    op.create_table(
        "integration_sync_jobs",
        sa.Column("connection_id", sa.Uuid(), nullable=False),
        sa.Column("integration_key", sa.String(length=60), nullable=False),
        sa.Column("entity", sa.String(length=40), nullable=False),
        sa.Column("direction", sa.String(length=16), nullable=False),
        sa.Column("mode", sa.String(length=16), nullable=False),
        sa.Column("status", sa.String(length=16), server_default="pending", nullable=False),
        sa.Column("cursor", sa.String(length=200), nullable=True),
        sa.Column(
            "stats", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False
        ),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_error", sa.String(length=300), nullable=True),
        sa.Column("error_code", sa.String(length=64), nullable=True),
        sa.Column("attempt_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("requested_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("environment_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "direction IN ('pull', 'push', 'bidirectional')",
            name=op.f("ck_integration_sync_jobs_direction"),
        ),
        sa.CheckConstraint(
            "mode IN ('incremental', 'full')", name=op.f("ck_integration_sync_jobs_mode")
        ),
        sa.CheckConstraint(
            "status IN ('pending', 'running', 'succeeded', 'failed', 'dead_letter', 'cancelled', 'paused')",
            name=op.f("ck_integration_sync_jobs_status"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "environment_id", "connection_id"],
            [
                "integration_connections.tenant_id",
                "integration_connections.environment_id",
                "integration_connections.id",
            ],
            name="fk_integration_sync_jobs_connection_id",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "environment_id"],
            ["environments.tenant_id", "environments.id"],
            name="fk_integration_sync_jobs_environment",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_integration_sync_jobs_tenant_id_tenants"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_integration_sync_jobs")),
        sa.UniqueConstraint(
            "tenant_id", "environment_id", "id", name="uq_integration_sync_jobs_scope_id"
        ),
    )
    op.create_index(
        "ix_integration_sync_jobs_scope",
        "integration_sync_jobs",
        ["tenant_id", "environment_id", "created_at"],
        unique=False,
    )
    op.create_index(
        "uq_integration_sync_jobs_active",
        "integration_sync_jobs",
        ["connection_id", "entity"],
        unique=True,
        postgresql_where=sa.text("status IN ('pending', 'running')"),
    )
    op.create_table(
        "integration_sync_attempts",
        sa.Column("job_id", sa.Uuid(), nullable=False),
        sa.Column("attempt", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error_code", sa.String(length=64), nullable=True),
        sa.Column(
            "stats", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False
        ),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("environment_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "environment_id", "job_id"],
            [
                "integration_sync_jobs.tenant_id",
                "integration_sync_jobs.environment_id",
                "integration_sync_jobs.id",
            ],
            name="fk_integration_sync_attempts_job_id",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "environment_id"],
            ["environments.tenant_id", "environments.id"],
            name="fk_integration_sync_attempts_environment",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_integration_sync_attempts_tenant_id_tenants"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_integration_sync_attempts")),
        sa.UniqueConstraint("job_id", "attempt", name="uq_integration_sync_attempts_attempt"),
        sa.UniqueConstraint(
            "tenant_id", "environment_id", "id", name="uq_integration_sync_attempts_scope_id"
        ),
    )
    op.create_table(
        "integration_sync_conflicts",
        sa.Column("job_id", sa.Uuid(), nullable=False),
        sa.Column("connection_id", sa.Uuid(), nullable=False),
        sa.Column("entity", sa.String(length=40), nullable=False),
        sa.Column("external_id", sa.String(length=200), nullable=False),
        sa.Column("reason", sa.String(length=200), nullable=False),
        sa.Column("status", sa.String(length=16), server_default="open", nullable=False),
        sa.Column(
            "details", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False
        ),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("environment_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('open', 'resolved', 'ignored')",
            name=op.f("ck_integration_sync_conflicts_status"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "environment_id", "connection_id"],
            [
                "integration_connections.tenant_id",
                "integration_connections.environment_id",
                "integration_connections.id",
            ],
            name="fk_integration_sync_conflicts_connection_id",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "environment_id", "job_id"],
            [
                "integration_sync_jobs.tenant_id",
                "integration_sync_jobs.environment_id",
                "integration_sync_jobs.id",
            ],
            name="fk_integration_sync_conflicts_job_id",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "environment_id"],
            ["environments.tenant_id", "environments.id"],
            name="fk_integration_sync_conflicts_environment",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_integration_sync_conflicts_tenant_id_tenants"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_integration_sync_conflicts")),
        sa.UniqueConstraint(
            "tenant_id", "environment_id", "id", name="uq_integration_sync_conflicts_scope_id"
        ),
    )
    # ### end Alembic commands ###
    op.execute(BACKFILL)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("integration_sync_conflicts")
    op.drop_table("integration_sync_attempts")
    op.drop_index(
        "uq_integration_sync_jobs_active",
        table_name="integration_sync_jobs",
        postgresql_where=sa.text("status IN ('pending', 'running')"),
    )
    op.drop_index("ix_integration_sync_jobs_scope", table_name="integration_sync_jobs")
    op.drop_table("integration_sync_jobs")
    op.drop_table("integration_sync_cursors")
    op.drop_table("integration_oauth_states")
    op.drop_index(
        "ix_integration_inbound_events_scope_status", table_name="integration_inbound_events"
    )
    op.drop_index("ix_integration_inbound_events_received", table_name="integration_inbound_events")
    op.drop_table("integration_inbound_events")
    op.drop_table("integration_external_refs")
    op.drop_index("ix_integration_deliveries_subscription", table_name="integration_deliveries")
    op.drop_index("ix_integration_deliveries_due", table_name="integration_deliveries")
    op.drop_table("integration_deliveries")
    op.drop_index("ix_integration_activities_connection", table_name="integration_activities")
    op.drop_table("integration_activities")
    op.drop_index("ix_outbox_events_scope_created", table_name="outbox_events")
    op.drop_index("ix_outbox_events_pending", table_name="outbox_events")
    op.drop_table("outbox_events")
    op.drop_index(
        "ix_integration_webhook_subscriptions_scope", table_name="integration_webhook_subscriptions"
    )
    op.drop_table("integration_webhook_subscriptions")
    op.drop_index(
        "uq_integration_connections_webhook_token",
        table_name="integration_connections",
        postgresql_where=sa.text("webhook_token_hash IS NOT NULL"),
    )
    op.drop_index("ix_integration_connections_scope_key", table_name="integration_connections")
    op.drop_table("integration_connections")
    op.drop_index("ix_api_keys_scope", table_name="api_keys")
    op.drop_table("api_keys")
    # ### end Alembic commands ###
