"""Employee self-onboarding links and personal details on employees.

Revision ID: 0005_employee_onboarding
Revises: 0004_integration_platform

Autogenerated and reviewed; the employees CHECK constraints were added by hand
(autogenerate does not detect constraints on existing tables). Personal details are
stored encrypted (application-level Fernet); only a keyed CNIC hash is queryable.
"""

import sqlalchemy as sa
from alembic import op

revision = "0005_employee_onboarding"
down_revision = "0004_integration_platform"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "employee_onboardings",
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=16), server_default="pending", nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("invited_name", sa.String(length=160), nullable=True),
        sa.Column("invited_email", sa.String(length=254), nullable=True),
        sa.Column("invited_designation", sa.String(length=120), nullable=True),
        sa.Column("created_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("created_by_label", sa.String(length=80), nullable=False),
        sa.Column("full_name", sa.String(length=160), nullable=True),
        sa.Column("email", sa.String(length=254), nullable=True),
        sa.Column("designation", sa.String(length=120), nullable=True),
        sa.Column("date_of_joining", sa.Date(), nullable=True),
        sa.Column("job_type", sa.String(length=16), nullable=True),
        sa.Column("details_encrypted", sa.Text(), nullable=True),
        sa.Column("cnic_hash", sa.String(length=64), nullable=True),
        sa.Column("submitted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("reviewed_by_label", sa.String(length=80), nullable=True),
        sa.Column("review_note", sa.String(length=500), nullable=True),
        sa.Column("employee_id", sa.Uuid(), nullable=True),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("environment_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('pending', 'submitted', 'approved', 'rejected', 'revoked')",
            name=op.f("ck_employee_onboardings_status"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "environment_id", "employee_id"],
            ["employees.tenant_id", "employees.environment_id", "employees.id"],
            name="fk_employee_onboardings_employee_id",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "environment_id"],
            ["environments.tenant_id", "environments.id"],
            name="fk_employee_onboardings_environment",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_employee_onboardings_tenant_id_tenants"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_employee_onboardings")),
        sa.UniqueConstraint(
            "tenant_id", "environment_id", "id", name="uq_employee_onboardings_scope_id"
        ),
    )
    op.create_index(
        "ix_employee_onboardings_scope_status",
        "employee_onboardings",
        ["tenant_id", "environment_id", "status"],
        unique=False,
    )
    op.create_index(
        "uq_employee_onboardings_token_hash", "employee_onboardings", ["token_hash"], unique=True
    )
    op.add_column("employees", sa.Column("gender", sa.String(length=8), nullable=True))
    op.add_column("employees", sa.Column("date_of_birth", sa.Date(), nullable=True))
    op.add_column("employees", sa.Column("work_arrangement", sa.String(length=16), nullable=True))
    op.add_column("employees", sa.Column("personal_details_encrypted", sa.Text(), nullable=True))
    op.add_column("employees", sa.Column("cnic_hash", sa.String(length=64), nullable=True))
    op.create_index(
        "ix_employees_cnic_hash",
        "employees",
        ["tenant_id", "environment_id", "cnic_hash"],
        unique=False,
    )
    op.create_check_constraint(
        "gender", "employees", "gender IS NULL OR gender IN ('male', 'female')"
    )
    op.create_check_constraint(
        "work_arrangement",
        "employees",
        "work_arrangement IS NULL OR work_arrangement IN "
        "('onsite', 'hybrid', 'remote', 'freelancer')",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("work_arrangement", "employees", type_="check")
    op.drop_constraint("gender", "employees", type_="check")
    op.drop_index("ix_employees_cnic_hash", table_name="employees")
    op.drop_column("employees", "cnic_hash")
    op.drop_column("employees", "personal_details_encrypted")
    op.drop_column("employees", "work_arrangement")
    op.drop_column("employees", "date_of_birth")
    op.drop_column("employees", "gender")
    op.drop_index("uq_employee_onboardings_token_hash", table_name="employee_onboardings")
    op.drop_index("ix_employee_onboardings_scope_status", table_name="employee_onboardings")
    op.drop_table("employee_onboardings")
    # ### end Alembic commands ###
