"""pi_saas

Revision ID: 0007_pi_saas
Revises: 3ad535597720
"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision = "0007_pi_saas"
down_revision = "3ad535597720"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "pi_billing_events",
        sa.Column("provider", sa.String(length=16), nullable=False),
        sa.Column("event_id", sa.String(length=120), nullable=False),
        sa.Column("event_type", sa.String(length=80), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=True),
        sa.Column("status", sa.String(length=16), server_default="received", nullable=False),
        sa.Column(
            "payload", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False
        ),
        sa.Column("attempts", sa.Integer(), server_default="0", nullable=False),
        sa.Column("error_code", sa.String(length=64), nullable=True),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('received', 'processed', 'ignored', 'failed')",
            name=op.f("ck_pi_billing_events_status"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_pi_billing_events")),
        sa.UniqueConstraint("provider", "event_id", name="uq_pi_billing_events_event"),
    )
    op.create_table(
        "pi_plans",
        sa.Column("key", sa.String(length=32), nullable=False),
        sa.Column("name", sa.String(length=80), nullable=False),
        sa.Column("description", sa.String(length=300), server_default="", nullable=False),
        sa.Column("status", sa.String(length=16), server_default="draft", nullable=False),
        sa.Column("sort_order", sa.Integer(), server_default="0", nullable=False),
        sa.Column("monthly_price", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("currency", sa.String(length=3), server_default="USD", nullable=False),
        sa.Column("trial_days", sa.Integer(), server_default="14", nullable=False),
        sa.Column(
            "allowances",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
        ),
        sa.Column(
            "features", postgresql.ARRAY(sa.String(length=40)), server_default="{}", nullable=False
        ),
        sa.Column("stripe_price_id", sa.String(length=120), nullable=True),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('draft', 'available', 'retired')", name=op.f("ck_pi_plans_status")
        ),
        sa.CheckConstraint(
            "monthly_price IS NULL OR monthly_price >= 0",
            name=op.f("ck_pi_plans_price_nonnegative"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_pi_plans")),
        sa.UniqueConstraint("key", name=op.f("uq_pi_plans_key")),
    )
    op.create_table(
        "pi_provider_events",
        sa.Column("provider", sa.String(length=16), nullable=False),
        sa.Column("idempotency_key", sa.String(length=128), nullable=False),
        sa.Column("event_type", sa.String(length=80), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=True),
        sa.Column("environment_id", sa.Uuid(), nullable=True),
        sa.Column("status", sa.String(length=16), server_default="received", nullable=False),
        sa.Column(
            "payload", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False
        ),
        sa.Column("duplicate_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("attempts", sa.Integer(), server_default="0", nullable=False),
        sa.Column("error_code", sa.String(length=64), nullable=True),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('received', 'processed', 'ignored', 'failed')",
            name=op.f("ck_pi_provider_events_status"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_pi_provider_events")),
        sa.UniqueConstraint("provider", "idempotency_key", name="uq_pi_provider_events_key"),
    )
    op.create_table(
        "pi_business_accounts",
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("business_category", sa.String(length=60), server_default="", nullable=False),
        sa.Column("language", sa.String(length=16), server_default="en", nullable=False),
        sa.Column("timezone", sa.String(length=64), server_default="UTC", nullable=False),
        sa.Column("country", sa.String(length=2), server_default="", nullable=False),
        sa.Column("website", sa.String(length=300), server_default="", nullable=False),
        sa.Column("description", sa.Text(), server_default="", nullable=False),
        sa.Column("offer_type", sa.String(length=16), server_default="services", nullable=False),
        sa.Column(
            "goals", postgresql.ARRAY(sa.String(length=40)), server_default="{}", nullable=False
        ),
        sa.Column(
            "automation_mode", sa.String(length=20), server_default="human_approved", nullable=False
        ),
        sa.Column("setup_state", sa.String(length=20), server_default="draft", nullable=False),
        sa.Column("onboarding_step", sa.Integer(), server_default="1", nullable=False),
        sa.Column(
            "onboarding_data",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
        ),
        sa.Column("status", sa.String(length=16), server_default="active", nullable=False),
        sa.Column("production_environment_id", sa.Uuid(), nullable=False),
        sa.Column("test_environment_id", sa.Uuid(), nullable=False),
        sa.Column("help_requested_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("launched_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("paused_reason", sa.String(length=200), nullable=True),
        sa.Column("created_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "automation_mode IN ('human_approved', 'mixed', 'ai_led')",
            name=op.f("ck_pi_business_accounts_automation_mode"),
        ),
        sa.CheckConstraint(
            "offer_type IN ('services', 'products', 'both')",
            name=op.f("ck_pi_business_accounts_offer_type"),
        ),
        sa.CheckConstraint(
            "setup_state IN ('draft', 'awaiting_connection', 'pending_approval', 'ready', 'active', 'paused', 'action_required')",
            name=op.f("ck_pi_business_accounts_setup_state"),
        ),
        sa.CheckConstraint(
            "status IN ('active', 'suspended', 'closed')",
            name=op.f("ck_pi_business_accounts_status"),
        ),
        sa.CheckConstraint(
            "onboarding_step BETWEEN 1 AND 5", name=op.f("ck_pi_business_accounts_onboarding_step")
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_pi_business_accounts_tenant_id_tenants"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_pi_business_accounts")),
        sa.UniqueConstraint("tenant_id", name="uq_pi_business_accounts_tenant"),
    )
    op.create_table(
        "pi_operator_members",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("role", sa.String(length=32), nullable=False),
        sa.Column("status", sa.String(length=16), server_default="active", nullable=False),
        sa.Column(
            "overrides", postgresql.ARRAY(sa.String(length=60)), server_default="{}", nullable=False
        ),
        sa.Column("added_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "role IN ('owner', 'operations_admin', 'onboarding_specialist', 'support', 'billing', 'analyst')",
            name=op.f("ck_pi_operator_members_role"),
        ),
        sa.CheckConstraint(
            "status IN ('active', 'revoked')", name=op.f("ck_pi_operator_members_status")
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["platform_users.id"],
            name=op.f("fk_pi_operator_members_user_id_platform_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_pi_operator_members")),
        sa.UniqueConstraint("user_id", name="uq_pi_operator_members_user"),
    )
    op.create_table(
        "pi_platform_invoices",
        sa.Column("number", sa.String(length=60), server_default="", nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("amount_due", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column(
            "amount_paid", sa.Numeric(precision=12, scale=2), server_default="0", nullable=False
        ),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("period_start", sa.DateTime(timezone=True), nullable=True),
        sa.Column("period_end", sa.DateTime(timezone=True), nullable=True),
        sa.Column("external_id", sa.String(length=120), nullable=True),
        sa.Column("hosted_url", sa.String(length=500), nullable=True),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('draft', 'open', 'paid', 'void', 'uncollectible')",
            name=op.f("ck_pi_platform_invoices_status"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_pi_platform_invoices_tenant_id_tenants"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_pi_platform_invoices")),
        sa.UniqueConstraint("external_id", name="uq_pi_platform_invoices_external"),
    )
    op.create_table(
        "pi_subscriptions",
        sa.Column("plan_key", sa.String(length=32), nullable=False),
        sa.Column("pending_plan_key", sa.String(length=32), nullable=True),
        sa.Column("status", sa.String(length=16), server_default="trialing", nullable=False),
        sa.Column("trial_ends_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("current_period_start", sa.DateTime(timezone=True), nullable=True),
        sa.Column("current_period_end", sa.DateTime(timezone=True), nullable=True),
        sa.Column("grace_ends_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("cancel_at_period_end", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("canceled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "billing_provider", sa.String(length=16), server_default="manual", nullable=False
        ),
        sa.Column("external_customer_id", sa.String(length=120), nullable=True),
        sa.Column("external_subscription_id", sa.String(length=120), nullable=True),
        sa.Column("spend_limit", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("currency", sa.String(length=3), server_default="USD", nullable=False),
        sa.Column("last_event_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "billing_provider IN ('manual', 'stripe')",
            name=op.f("ck_pi_subscriptions_billing_provider"),
        ),
        sa.CheckConstraint(
            "status IN ('trialing', 'active', 'past_due', 'canceled', 'suspended')",
            name=op.f("ck_pi_subscriptions_status"),
        ),
        sa.CheckConstraint(
            "spend_limit IS NULL OR spend_limit >= 0", name=op.f("ck_pi_subscriptions_spend_limit")
        ),
        sa.ForeignKeyConstraint(
            ["plan_key"],
            ["pi_plans.key"],
            name=op.f("fk_pi_subscriptions_plan_key_pi_plans"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_pi_subscriptions_tenant_id_tenants"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_pi_subscriptions")),
        sa.UniqueConstraint("tenant_id", name="uq_pi_subscriptions_tenant"),
    )
    op.create_index(
        "ix_pi_subscriptions_external",
        "pi_subscriptions",
        ["external_subscription_id"],
        unique=False,
    )
    op.create_table(
        "pi_support_grants",
        sa.Column("operator_user_id", sa.Uuid(), nullable=True),
        sa.Column("scope", sa.String(length=20), nullable=False),
        sa.Column("status", sa.String(length=16), server_default="requested", nullable=False),
        sa.Column("reason", sa.String(length=300), server_default="", nullable=False),
        sa.Column("requested_by", sa.String(length=16), server_default="client", nullable=False),
        sa.Column("approved_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "scope IN ('configuration', 'conversations', 'full_support')",
            name=op.f("ck_pi_support_grants_scope"),
        ),
        sa.CheckConstraint(
            "status IN ('requested', 'active', 'revoked', 'expired', 'declined')",
            name=op.f("ck_pi_support_grants_status"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_pi_support_grants_tenant_id_tenants"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_pi_support_grants")),
    )
    op.create_index(
        "ix_pi_support_grants_operator",
        "pi_support_grants",
        ["operator_user_id", "status"],
        unique=False,
    )
    op.create_table(
        "pi_bookable_services",
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("duration_minutes", sa.Integer(), server_default="30", nullable=False),
        sa.Column("buffer_minutes", sa.Integer(), server_default="0", nullable=False),
        sa.Column(
            "working_hours",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
        ),
        sa.Column(
            "staff_user_ids", postgresql.ARRAY(sa.Uuid()), server_default="{}", nullable=False
        ),
        sa.Column("calendar_connection_id", sa.Uuid(), nullable=True),
        sa.Column("status", sa.String(length=16), server_default="active", nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("environment_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('active', 'archived')", name=op.f("ck_pi_bookable_services_status")
        ),
        sa.CheckConstraint(
            "buffer_minutes BETWEEN 0 AND 240", name=op.f("ck_pi_bookable_services_buffer")
        ),
        sa.CheckConstraint(
            "duration_minutes BETWEEN 5 AND 720", name=op.f("ck_pi_bookable_services_duration")
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "environment_id"],
            ["environments.tenant_id", "environments.id"],
            name="fk_pi_bookable_services_environment",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_pi_bookable_services_tenant_id_tenants"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_pi_bookable_services")),
        sa.UniqueConstraint(
            "tenant_id", "environment_id", "id", name="uq_pi_bookable_services_scope_id"
        ),
    )
    op.create_table(
        "pi_campaigns",
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("template_name", sa.String(length=512), nullable=False),
        sa.Column("template_language", sa.String(length=16), nullable=False),
        sa.Column("audience_tag", sa.String(length=40), nullable=True),
        sa.Column("status", sa.String(length=16), server_default="draft", nullable=False),
        sa.Column("scheduled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("max_recipients", sa.Integer(), server_default="500", nullable=False),
        sa.Column(
            "results", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False
        ),
        sa.Column("created_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("environment_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('draft', 'scheduled', 'sending', 'completed', 'cancelled')",
            name=op.f("ck_pi_campaigns_status"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "environment_id"],
            ["environments.tenant_id", "environments.id"],
            name="fk_pi_campaigns_environment",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_pi_campaigns_tenant_id_tenants"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_pi_campaigns")),
        sa.UniqueConstraint("tenant_id", "environment_id", "id", name="uq_pi_campaigns_scope_id"),
    )
    op.create_table(
        "pi_customer_consents",
        sa.Column("customer_id", sa.Uuid(), nullable=False),
        sa.Column("purpose", sa.String(length=16), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("source", sa.String(length=300), server_default="", nullable=False),
        sa.Column("source_message_id", sa.Uuid(), nullable=True),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("environment_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "purpose IN ('reminders', 'marketing')", name=op.f("ck_pi_customer_consents_purpose")
        ),
        sa.CheckConstraint(
            "status IN ('granted', 'withdrawn')", name=op.f("ck_pi_customer_consents_status")
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "environment_id"],
            ["environments.tenant_id", "environments.id"],
            name="fk_pi_customer_consents_environment",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_pi_customer_consents_tenant_id_tenants"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_pi_customer_consents")),
        sa.UniqueConstraint(
            "tenant_id", "environment_id", "customer_id", "purpose", name="uq_pi_consent_purpose"
        ),
        sa.UniqueConstraint(
            "tenant_id", "environment_id", "id", name="uq_pi_customer_consents_scope_id"
        ),
    )
    op.create_table(
        "pi_knowledge_drafts",
        sa.Column("origin", sa.String(length=16), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("source_text", sa.Text(), server_default="", nullable=False),
        sa.Column("customer_visible", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("status", sa.String(length=16), server_default="draft", nullable=False),
        sa.Column("created_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("published_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("published_document_id", sa.Uuid(), nullable=True),
        sa.Column("staff_request_id", sa.Uuid(), nullable=True),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("environment_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "origin IN ('owner_text', 'owner_upload', 'owner_audio', 'ask_owner', 'website')",
            name=op.f("ck_pi_knowledge_drafts_origin"),
        ),
        sa.CheckConstraint(
            "status IN ('draft', 'published', 'discarded')",
            name=op.f("ck_pi_knowledge_drafts_status"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "environment_id"],
            ["environments.tenant_id", "environments.id"],
            name="fk_pi_knowledge_drafts_environment",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_pi_knowledge_drafts_tenant_id_tenants"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_pi_knowledge_drafts")),
        sa.UniqueConstraint(
            "tenant_id", "environment_id", "id", name="uq_pi_knowledge_drafts_scope_id"
        ),
    )
    op.create_table(
        "pi_operator_assignments",
        sa.Column("operator_id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["operator_id"],
            ["pi_operator_members.id"],
            name=op.f("fk_pi_operator_assignments_operator_id_pi_operator_members"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_pi_operator_assignments_tenant_id_tenants"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_pi_operator_assignments")),
        sa.UniqueConstraint("operator_id", "tenant_id", name="uq_pi_operator_assignments_entry"),
    )
    op.create_table(
        "pi_saved_replies",
        sa.Column("title", sa.String(length=120), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("environment_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "environment_id"],
            ["environments.tenant_id", "environments.id"],
            name="fk_pi_saved_replies_environment",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_pi_saved_replies_tenant_id_tenants"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_pi_saved_replies")),
        sa.UniqueConstraint(
            "tenant_id", "environment_id", "id", name="uq_pi_saved_replies_scope_id"
        ),
        sa.UniqueConstraint(
            "tenant_id", "environment_id", "title", name="uq_pi_saved_replies_title"
        ),
    )
    op.create_table(
        "pi_tasks",
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), server_default="", nullable=False),
        sa.Column("customer_id", sa.Uuid(), nullable=True),
        sa.Column("conversation_id", sa.Uuid(), nullable=True),
        sa.Column("assignee_user_id", sa.Uuid(), nullable=True),
        sa.Column("created_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("created_by_label", sa.String(length=80), server_default="", nullable=False),
        sa.Column("status", sa.String(length=16), server_default="open", nullable=False),
        sa.Column("priority", sa.String(length=8), server_default="normal", nullable=False),
        sa.Column("due_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "customer_visible_status", sa.String(length=300), server_default="", nullable=False
        ),
        sa.Column("idempotency_key", sa.String(length=200), nullable=True),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("environment_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "priority IN ('low', 'normal', 'high', 'urgent')", name=op.f("ck_pi_tasks_priority")
        ),
        sa.CheckConstraint(
            "status IN ('open', 'in_progress', 'blocked', 'done', 'cancelled')",
            name=op.f("ck_pi_tasks_status"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "environment_id"],
            ["environments.tenant_id", "environments.id"],
            name="fk_pi_tasks_environment",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_pi_tasks_tenant_id_tenants"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_pi_tasks")),
        sa.UniqueConstraint("tenant_id", "environment_id", "id", name="uq_pi_tasks_scope_id"),
        sa.UniqueConstraint(
            "tenant_id", "environment_id", "idempotency_key", name="uq_pi_tasks_idempotency"
        ),
    )
    op.create_table(
        "pi_tickets",
        sa.Column("subject", sa.String(length=200), nullable=False),
        sa.Column("summary", sa.Text(), server_default="", nullable=False),
        sa.Column("customer_id", sa.Uuid(), nullable=False),
        sa.Column("conversation_id", sa.Uuid(), nullable=True),
        sa.Column("team", sa.String(length=60), server_default="support", nullable=False),
        sa.Column("assignee_user_id", sa.Uuid(), nullable=True),
        sa.Column("status", sa.String(length=20), server_default="open", nullable=False),
        sa.Column("priority", sa.String(length=8), server_default="normal", nullable=False),
        sa.Column("first_response_due_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("first_responded_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("idempotency_key", sa.String(length=200), nullable=True),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("environment_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "priority IN ('low', 'normal', 'high', 'urgent')", name=op.f("ck_pi_tickets_priority")
        ),
        sa.CheckConstraint(
            "status IN ('open', 'pending_customer', 'resolved', 'closed')",
            name=op.f("ck_pi_tickets_status"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "environment_id"],
            ["environments.tenant_id", "environments.id"],
            name="fk_pi_tickets_environment",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_pi_tickets_tenant_id_tenants"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_pi_tickets")),
        sa.UniqueConstraint("tenant_id", "environment_id", "id", name="uq_pi_tickets_scope_id"),
        sa.UniqueConstraint(
            "tenant_id", "environment_id", "idempotency_key", name="uq_pi_tickets_idempotency"
        ),
    )
    op.create_table(
        "pi_usage_counters",
        sa.Column("period", sa.Date(), nullable=False),
        sa.Column("metric", sa.String(length=24), nullable=False),
        sa.Column(
            "quantity", sa.Numeric(precision=20, scale=6), server_default="0", nullable=False
        ),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("environment_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "metric IN ('messages_in', 'messages_out', 'template_messages', 'ai_tokens', 'ai_cost', 'media_items', 'media_seconds', 'storage_bytes')",
            name=op.f("ck_pi_usage_counters_metric"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "environment_id"],
            ["environments.tenant_id", "environments.id"],
            name="fk_pi_usage_counters_environment",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_pi_usage_counters_tenant_id_tenants"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_pi_usage_counters")),
        sa.UniqueConstraint(
            "tenant_id", "environment_id", "id", name="uq_pi_usage_counters_scope_id"
        ),
        sa.UniqueConstraint(
            "tenant_id", "environment_id", "period", "metric", name="uq_pi_usage_counters_metric"
        ),
    )
    op.create_table(
        "pi_bookings",
        sa.Column("service_id", sa.Uuid(), nullable=False),
        sa.Column("customer_id", sa.Uuid(), nullable=False),
        sa.Column("conversation_id", sa.Uuid(), nullable=True),
        sa.Column("staff_user_id", sa.Uuid(), nullable=True),
        sa.Column("starts_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ends_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("timezone", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=16), server_default="pending", nullable=False),
        sa.Column("notes", sa.Text(), server_default="", nullable=False),
        sa.Column("idempotency_key", sa.String(length=200), nullable=False),
        sa.Column("external_event_id", sa.String(length=200), nullable=True),
        sa.Column("external_sync", sa.String(length=16), server_default="none", nullable=False),
        sa.Column("created_by_label", sa.String(length=80), server_default="", nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("environment_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('pending', 'confirmed', 'cancelled', 'completed', 'no_show')",
            name=op.f("ck_pi_bookings_status"),
        ),
        sa.CheckConstraint("ends_at > starts_at", name=op.f("ck_pi_bookings_interval")),
        sa.ForeignKeyConstraint(
            ["tenant_id", "environment_id", "service_id"],
            [
                "pi_bookable_services.tenant_id",
                "pi_bookable_services.environment_id",
                "pi_bookable_services.id",
            ],
            name="fk_pi_bookings_service_id",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "environment_id"],
            ["environments.tenant_id", "environments.id"],
            name="fk_pi_bookings_environment",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_pi_bookings_tenant_id_tenants"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_pi_bookings")),
        sa.UniqueConstraint("tenant_id", "environment_id", "id", name="uq_pi_bookings_scope_id"),
        sa.UniqueConstraint(
            "tenant_id", "environment_id", "idempotency_key", name="uq_pi_bookings_idempotency"
        ),
    )
    op.create_table(
        "pi_provider_connections",
        sa.Column("provider", sa.String(length=16), server_default="kapso", nullable=False),
        sa.Column("status", sa.String(length=20), server_default="draft", nullable=False),
        sa.Column("external_customer_id", sa.String(length=120), nullable=True),
        sa.Column("setup_link_id", sa.String(length=120), nullable=True),
        sa.Column("setup_link_url", sa.String(length=1000), nullable=True),
        sa.Column("setup_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("setup_status", sa.String(length=20), nullable=True),
        sa.Column("connection_type", sa.String(length=16), nullable=True),
        sa.Column("phone_number_id", sa.String(length=32), nullable=True),
        sa.Column("display_phone_number", sa.String(length=32), nullable=True),
        sa.Column("business_account_id", sa.String(length=32), nullable=True),
        sa.Column("whatsapp_connection_id", sa.Uuid(), nullable=True),
        sa.Column(
            "health", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False
        ),
        sa.Column("health_checked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "number_request",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
        ),
        sa.Column("last_event_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_error_code", sa.String(length=64), nullable=True),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("environment_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "connection_type IS NULL OR connection_type IN ('coexistence', 'dedicated')",
            name=op.f("ck_pi_provider_connections_connection_type"),
        ),
        sa.CheckConstraint(
            "provider IN ('kapso', 'meta_cloud')", name=op.f("ck_pi_provider_connections_provider")
        ),
        sa.CheckConstraint(
            "status IN ('draft', 'setup_pending', 'connected', 'action_required', 'disconnected')",
            name=op.f("ck_pi_provider_connections_status"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "environment_id", "whatsapp_connection_id"],
            [
                "whatsapp_connections.tenant_id",
                "whatsapp_connections.environment_id",
                "whatsapp_connections.id",
            ],
            name="fk_pi_provider_connections_whatsapp_connection_id",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "environment_id"],
            ["environments.tenant_id", "environments.id"],
            name="fk_pi_provider_connections_environment",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_pi_provider_connections_tenant_id_tenants"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_pi_provider_connections")),
        sa.UniqueConstraint(
            "tenant_id", "environment_id", "id", name="uq_pi_provider_connections_scope_id"
        ),
    )
    op.create_index(
        "ix_pi_provider_connections_number",
        "pi_provider_connections",
        ["provider", "phone_number_id"],
        unique=False,
    )
    op.create_table(
        "pi_conversation_notes",
        sa.Column("conversation_id", sa.Uuid(), nullable=False),
        sa.Column("author_user_id", sa.Uuid(), nullable=True),
        sa.Column("author_label", sa.String(length=80), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("environment_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "environment_id", "conversation_id"],
            [
                "pi_conversations.tenant_id",
                "pi_conversations.environment_id",
                "pi_conversations.id",
            ],
            name="fk_pi_conversation_notes_conversation_id",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "environment_id"],
            ["environments.tenant_id", "environments.id"],
            name="fk_pi_conversation_notes_environment",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_pi_conversation_notes_tenant_id_tenants"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_pi_conversation_notes")),
        sa.UniqueConstraint(
            "tenant_id", "environment_id", "id", name="uq_pi_conversation_notes_scope_id"
        ),
    )
    op.create_table(
        "pi_conversation_tags",
        sa.Column("conversation_id", sa.Uuid(), nullable=False),
        sa.Column("tag", sa.String(length=40), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("environment_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "environment_id", "conversation_id"],
            [
                "pi_conversations.tenant_id",
                "pi_conversations.environment_id",
                "pi_conversations.id",
            ],
            name="fk_pi_conversation_tags_conversation_id",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "environment_id"],
            ["environments.tenant_id", "environments.id"],
            name="fk_pi_conversation_tags_environment",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_pi_conversation_tags_tenant_id_tenants"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_pi_conversation_tags")),
        sa.UniqueConstraint(
            "tenant_id", "environment_id", "conversation_id", "tag", name="uq_pi_conversation_tag"
        ),
        sa.UniqueConstraint(
            "tenant_id", "environment_id", "id", name="uq_pi_conversation_tags_scope_id"
        ),
    )
    op.create_table(
        "pi_staff_requests",
        sa.Column("conversation_id", sa.Uuid(), nullable=False),
        sa.Column("customer_id", sa.Uuid(), nullable=False),
        sa.Column("question", sa.Text(), nullable=False),
        sa.Column("context_summary", sa.Text(), server_default="", nullable=False),
        sa.Column("status", sa.String(length=16), server_default="open", nullable=False),
        sa.Column("answer", sa.Text(), nullable=True),
        sa.Column("answered_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("reply_message_id", sa.Uuid(), nullable=True),
        sa.Column("knowledge_document_id", sa.Uuid(), nullable=True),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("environment_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('open', 'answered', 'published', 'dismissed')",
            name=op.f("ck_pi_staff_requests_status"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "environment_id", "conversation_id"],
            [
                "pi_conversations.tenant_id",
                "pi_conversations.environment_id",
                "pi_conversations.id",
            ],
            name="fk_pi_staff_requests_conversation_id",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "environment_id"],
            ["environments.tenant_id", "environments.id"],
            name="fk_pi_staff_requests_environment",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_pi_staff_requests_tenant_id_tenants"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_pi_staff_requests")),
        sa.UniqueConstraint(
            "tenant_id", "environment_id", "id", name="uq_pi_staff_requests_scope_id"
        ),
    )
    op.create_index(
        "ix_pi_staff_requests_open",
        "pi_staff_requests",
        ["tenant_id", "environment_id", "status"],
        unique=False,
    )
    op.add_column(
        "auth_sessions",
        sa.Column("audience", sa.String(length=16), server_default="owner_os", nullable=False),
    )
    op.create_check_constraint(
        op.f("ck_auth_sessions_audience"), "auth_sessions", "audience IN ('owner_os', 'pi')"
    )
    op.drop_constraint(op.f("ck_pi_messages_status"), "pi_messages", type_="check")
    op.create_check_constraint(
        op.f("ck_pi_messages_status"),
        "pi_messages",
        "status IN ('received', 'processing', 'processed', 'skipped', 'failed', 'queued', "
        "'sent', 'delivered', 'read', 'pending_approval')",
    )
    op.drop_constraint(
        op.f("ck_whatsapp_connections_provider"), "whatsapp_connections", type_="check"
    )
    op.create_check_constraint(
        op.f("ck_whatsapp_connections_provider"),
        "whatsapp_connections",
        "provider IN ('meta_cloud', 'kapso')",
    )
    # Plans without prices: commercial prices are set by an operator before checkout is
    # possible. Allowances are default product limits for operator review, not tariffs.
    plans = sa.table(
        "pi_plans",
        sa.column("key", sa.String),
        sa.column("name", sa.String),
        sa.column("description", sa.String),
        sa.column("status", sa.String),
        sa.column("sort_order", sa.Integer),
        sa.column("trial_days", sa.Integer),
        sa.column("allowances", postgresql.JSONB),
        sa.column("features", postgresql.ARRAY(sa.String)),
    )
    op.bulk_insert(
        plans,
        [
            {
                "key": "starter",
                "name": "Starter",
                "description": "One WhatsApp number for a small team",
                "status": "available",
                "sort_order": 1,
                "trial_days": 14,
                "allowances": {
                    "messages": 1000,
                    "ai_tokens": 2000000,
                    "media_items": 200,
                    "storage_mb": 500,
                    "seats": 2,
                    "numbers": 1,
                },
                "features": ["inbox", "knowledge", "followups"],
            },
            {
                "key": "growth",
                "name": "Growth",
                "description": "More conversations, tools and teammates",
                "status": "available",
                "sort_order": 2,
                "trial_days": 14,
                "allowances": {
                    "messages": 5000,
                    "ai_tokens": 10000000,
                    "media_items": 1000,
                    "storage_mb": 2000,
                    "seats": 5,
                    "numbers": 2,
                },
                "features": ["inbox", "knowledge", "followups", "tools", "campaigns"],
            },
            {
                "key": "business",
                "name": "Business",
                "description": "Higher limits and advanced controls",
                "status": "available",
                "sort_order": 3,
                "trial_days": 14,
                "allowances": {
                    "messages": 20000,
                    "ai_tokens": 40000000,
                    "media_items": 5000,
                    "storage_mb": 10000,
                    "seats": 15,
                    "numbers": 5,
                },
                "features": [
                    "inbox",
                    "knowledge",
                    "followups",
                    "tools",
                    "campaigns",
                    "advanced_permissions",
                ],
            },
        ],
    )
    # New permissions for existing tenants. Existing roles that can use PI keep seeing
    # every conversation (pi.inbox.all), so no current user loses access.
    new_all = (
        "pi.inbox.all",
        "pi.inbox.assign",
        "pi.inbox.notes",
        "pi.customers.export",
        "pi.knowledge.publish",
        "pi.billing.read",
        "pi.billing.manage",
        "pi.support.grant",
        "pi.bookings.read",
        "pi.bookings.manage",
        "pi.work.read",
        "pi.work.manage",
    )
    grants = {
        "owner": new_all,
        "admin": new_all,
        "manager": (
            "pi.inbox.all",
            "pi.inbox.assign",
            "pi.inbox.notes",
            "pi.billing.read",
            "pi.bookings.read",
            "pi.bookings.manage",
            "pi.work.read",
            "pi.work.manage",
        ),
        "support": (
            "pi.inbox.all",
            "pi.inbox.notes",
            "pi.bookings.read",
            "pi.bookings.manage",
            "pi.work.read",
            "pi.work.manage",
        ),
        "viewer": ("pi.inbox.all", "pi.bookings.read", "pi.work.read"),
    }
    for key, permissions in grants.items():
        for permission in permissions:
            op.execute(
                sa.text(
                    "INSERT INTO role_permissions (id, tenant_id, role_id, permission) "
                    "SELECT gen_random_uuid(), r.tenant_id, r.id, :permission FROM roles r "
                    "WHERE r.is_system AND r.key = :key ON CONFLICT DO NOTHING"
                ).bindparams(key=key, permission=permission)
            )
    op.execute(
        "INSERT INTO role_permissions (id, tenant_id, role_id, permission) "
        "SELECT gen_random_uuid(), rp.tenant_id, rp.role_id, 'pi.inbox.all' "
        "FROM role_permissions rp JOIN roles r ON r.tenant_id = rp.tenant_id AND r.id = rp.role_id "
        "WHERE NOT r.is_system AND rp.permission = 'pi.read' ON CONFLICT DO NOTHING"
    )
    new_roles = {
        "member": (
            "Sales/Support member",
            "Handles conversations assigned to them",
            (
                "customers.read",
                "customers.write",
                "catalog.read",
                "orders.read",
                "pi.read",
                "pi.inbox.reply",
                "pi.handoffs.manage",
                "pi.memory.read",
                "pi.inbox.notes",
                "notifications.read",
                "pi.bookings.read",
                "pi.bookings.manage",
                "pi.work.read",
                "pi.work.manage",
            ),
        ),
        "billing": (
            "Billing",
            "Pi plan, usage and invoices",
            ("pi.billing.read", "pi.billing.manage", "overview.read", "notifications.read"),
        ),
    }
    for key, (name, description, permissions) in new_roles.items():
        op.execute(
            sa.text(
                "INSERT INTO roles (id, tenant_id, key, name, description, is_system) "
                "SELECT gen_random_uuid(), t.id, :key, :name, :description, true FROM tenants t "
                "ON CONFLICT (tenant_id, key) DO NOTHING"
            ).bindparams(key=key, name=name, description=description)
        )
        for permission in permissions:
            op.execute(
                sa.text(
                    "INSERT INTO role_permissions (id, tenant_id, role_id, permission) "
                    "SELECT gen_random_uuid(), r.tenant_id, r.id, :permission FROM roles r "
                    "WHERE r.is_system AND r.key = :key ON CONFLICT DO NOTHING"
                ).bindparams(key=key, permission=permission)
            )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        "DELETE FROM role_permissions WHERE permission IN ('pi.inbox.all', 'pi.inbox.assign', "
        "'pi.inbox.notes', 'pi.customers.export', 'pi.knowledge.publish', 'pi.billing.read', "
        "'pi.billing.manage', 'pi.support.grant', 'pi.bookings.read', 'pi.bookings.manage', "
        "'pi.work.read', 'pi.work.manage')"
    )
    op.execute(
        "DELETE FROM roles r WHERE r.is_system AND r.key IN ('member', 'billing') AND NOT EXISTS "
        "(SELECT 1 FROM membership_roles m WHERE m.tenant_id = r.tenant_id AND m.role_id = r.id)"
    )
    op.execute(
        "UPDATE pi_messages SET status = 'skipped', error_code = 'APPROVAL_REMOVED' "
        "WHERE status = 'pending_approval'"
    )
    op.drop_constraint(op.f("ck_pi_messages_status"), "pi_messages", type_="check")
    op.create_check_constraint(
        op.f("ck_pi_messages_status"),
        "pi_messages",
        "status IN ('received', 'processing', 'processed', 'skipped', 'failed', 'queued', "
        "'sent', 'delivered', 'read')",
    )
    op.execute("DELETE FROM whatsapp_connections WHERE provider = 'kapso'")
    op.drop_constraint(
        op.f("ck_whatsapp_connections_provider"), "whatsapp_connections", type_="check"
    )
    op.create_check_constraint(
        op.f("ck_whatsapp_connections_provider"),
        "whatsapp_connections",
        "provider IN ('meta_cloud')",
    )
    op.drop_constraint(op.f("ck_auth_sessions_audience"), "auth_sessions", type_="check")
    op.execute("DELETE FROM auth_sessions WHERE audience <> 'owner_os'")
    op.drop_column("auth_sessions", "audience")
    op.drop_index("ix_pi_staff_requests_open", table_name="pi_staff_requests")
    op.drop_table("pi_staff_requests")
    op.drop_table("pi_conversation_tags")
    op.drop_table("pi_conversation_notes")
    op.drop_index("ix_pi_provider_connections_number", table_name="pi_provider_connections")
    op.drop_table("pi_provider_connections")
    op.drop_table("pi_bookings")
    op.drop_table("pi_usage_counters")
    op.drop_table("pi_tickets")
    op.drop_table("pi_tasks")
    op.drop_table("pi_saved_replies")
    op.drop_table("pi_operator_assignments")
    op.drop_table("pi_knowledge_drafts")
    op.drop_table("pi_customer_consents")
    op.drop_table("pi_campaigns")
    op.drop_table("pi_bookable_services")
    op.drop_index("ix_pi_support_grants_operator", table_name="pi_support_grants")
    op.drop_table("pi_support_grants")
    op.drop_index("ix_pi_subscriptions_external", table_name="pi_subscriptions")
    op.drop_table("pi_subscriptions")
    op.drop_table("pi_platform_invoices")
    op.drop_table("pi_operator_members")
    op.drop_table("pi_business_accounts")
    op.drop_table("pi_provider_events")
    op.drop_table("pi_plans")
    op.drop_table("pi_billing_events")
    # ### end Alembic commands ###
