"""pi_subscription_collections

Revision ID: 0008_pi_billing
Revises: 0007_pi_saas
"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = "0008_pi_billing"
down_revision = "0007_pi_saas"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "pi_collection_settings",
        sa.Column("key", sa.String(length=20), nullable=False),
        sa.Column(
            "config", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False
        ),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_pi_collection_settings")),
        sa.UniqueConstraint("key", name=op.f("uq_pi_collection_settings_key")),
    )
    op.create_table(
        "pi_checkout_attempts",
        sa.Column("plan_key", sa.String(length=32), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("form", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("external_id", sa.String(length=120), nullable=True),
        sa.Column("url", sa.Text(), nullable=True),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_pi_checkout_attempts_tenant_id_tenants"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_pi_checkout_attempts")),
    )
    op.create_table(
        "pi_manual_payments",
        sa.Column("request_key", sa.Uuid(), nullable=False),
        sa.Column("plan_key", sa.String(length=32), nullable=False),
        sa.Column("plan_name", sa.String(length=80), nullable=False),
        sa.Column("method", sa.String(length=20), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("months", sa.Integer(), nullable=False),
        sa.Column("amount", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("instructions", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("payer_name", sa.String(length=160), server_default="", nullable=False),
        sa.Column("reference", sa.String(length=120), server_default="", nullable=False),
        sa.Column("reference_key", sa.String(length=64), nullable=True),
        sa.Column("paid_on", sa.Date(), nullable=True),
        sa.Column("note", sa.String(length=500), server_default="", nullable=False),
        sa.Column("proof", sa.LargeBinary(), nullable=True),
        sa.Column("proof_type", sa.String(length=40), nullable=True),
        sa.Column("proof_sha256", sa.String(length=64), nullable=True),
        sa.Column("created_by", sa.Uuid(), nullable=False),
        sa.Column("submitted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("reviewed_by", sa.Uuid(), nullable=True),
        sa.Column("review_note", sa.String(length=500), server_default="", nullable=False),
        sa.Column("receipt_number", sa.String(length=60), nullable=True),
        sa.Column("invoice_id", sa.Uuid(), nullable=False),
        sa.Column("period_start", sa.DateTime(timezone=True), nullable=True),
        sa.Column("period_end", sa.DateTime(timezone=True), nullable=True),
        sa.Column("previous_period_end", sa.DateTime(timezone=True), nullable=True),
        sa.Column("refunded_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("refund_reference", sa.String(length=120), nullable=True),
        sa.Column("refund_reason", sa.String(length=500), nullable=True),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "amount > 0 AND currency = 'PKR'", name=op.f("ck_pi_manual_payments_amount_currency")
        ),
        sa.CheckConstraint(
            "method IN ('bank_transfer', 'cash')", name=op.f("ck_pi_manual_payments_method")
        ),
        sa.CheckConstraint(
            "status IN ('awaiting_payment', 'submitted', 'approved', 'rejected', 'cancelled', 'refunded')",
            name=op.f("ck_pi_manual_payments_status"),
        ),
        sa.CheckConstraint("months IN (1, 3, 6, 12)", name=op.f("ck_pi_manual_payments_months")),
        sa.ForeignKeyConstraint(
            ["invoice_id"],
            ["pi_platform_invoices.id"],
            name=op.f("fk_pi_manual_payments_invoice_id_pi_platform_invoices"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["plan_key"],
            ["pi_plans.key"],
            name=op.f("fk_pi_manual_payments_plan_key_pi_plans"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_pi_manual_payments_tenant_id_tenants"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_pi_manual_payments")),
        sa.UniqueConstraint("receipt_number", name="uq_pi_manual_payment_receipt"),
        sa.UniqueConstraint("reference_key", name="uq_pi_manual_payment_reference"),
        sa.UniqueConstraint("tenant_id", "request_key", name="uq_pi_manual_payment_request"),
    )
    op.add_column(
        "pi_plans",
        sa.Column("manual_monthly_price_pkr", sa.Numeric(precision=12, scale=2), nullable=True),
    )
    op.create_check_constraint(
        "ck_pi_plans_manual_price_positive",
        "pi_plans",
        "manual_monthly_price_pkr IS NULL OR manual_monthly_price_pkr > 0",
    )
    op.add_column(
        "pi_platform_invoices",
        sa.Column("last_event_at", sa.DateTime(timezone=True), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("pi_platform_invoices", "last_event_at")
    op.drop_constraint("ck_pi_plans_manual_price_positive", "pi_plans", type_="check")
    op.drop_column("pi_plans", "manual_monthly_price_pkr")
    op.drop_table("pi_manual_payments")
    op.drop_table("pi_checkout_attempts")
    op.drop_table("pi_collection_settings")
    # ### end Alembic commands ###
