"""pi customer payments

Revision ID: 0009_pi_customer_payments
Revises: 0008_pi_billing
"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision = "0009_pi_customer_payments"
down_revision = "0008_pi_billing"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "pi_customer_payment_settings",
        sa.Column("stripe_enabled", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("bank_enabled", sa.Boolean(), server_default="false", nullable=False),
        sa.Column(
            "bank_accounts",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="[]",
            nullable=False,
        ),
        sa.Column("wallet_enabled", sa.Boolean(), server_default="false", nullable=False),
        sa.Column(
            "wallets", postgresql.JSONB(astext_type=sa.Text()), server_default="[]", nullable=False
        ),
        sa.Column("cash_enabled", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("cash_instructions", sa.Text(), server_default="", nullable=False),
        sa.Column("payment_note", sa.Text(), server_default="", nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("environment_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "environment_id"],
            ["environments.tenant_id", "environments.id"],
            name="fk_pi_customer_payment_settings_environment",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_pi_customer_payment_settings_tenant_id_tenants"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_pi_customer_payment_settings")),
        sa.UniqueConstraint(
            "tenant_id", "environment_id", "id", name="uq_pi_customer_payment_settings_scope_id"
        ),
        sa.UniqueConstraint("tenant_id", "environment_id", name="uq_pi_customer_payment_settings"),
    )
    op.create_table(
        "pi_payment_requests",
        sa.Column("invoice_id", sa.Uuid(), nullable=False),
        sa.Column("customer_id", sa.Uuid(), nullable=False),
        sa.Column("conversation_id", sa.Uuid(), nullable=True),
        sa.Column("method", sa.String(length=16), nullable=False),
        sa.Column("status", sa.String(length=24), server_default="open", nullable=False),
        sa.Column("amount", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("reference", sa.String(length=24), nullable=False),
        sa.Column(
            "instructions",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
        ),
        sa.Column("checkout_url", sa.String(length=500), nullable=True),
        sa.Column("integration_operation_id", sa.Uuid(), nullable=True),
        sa.Column("proof_note", sa.Text(), server_default="", nullable=False),
        sa.Column("proof_message_id", sa.Uuid(), nullable=True),
        sa.Column("verified_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("payment_id", sa.Uuid(), nullable=True),
        sa.Column("idempotency_key", sa.String(length=200), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_by_label", sa.String(length=80), server_default="", nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("environment_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "method IN ('stripe', 'bank_transfer', 'mobile_wallet', 'cash')",
            name=op.f("ck_pi_payment_requests_method"),
        ),
        sa.CheckConstraint(
            "status IN ('open', 'awaiting_verification', 'paid', 'cancelled', 'expired', 'needs_review')",
            name=op.f("ck_pi_payment_requests_status"),
        ),
        sa.CheckConstraint("amount > 0", name=op.f("ck_pi_payment_requests_amount_positive")),
        sa.ForeignKeyConstraint(
            ["tenant_id", "environment_id", "invoice_id"],
            ["invoices.tenant_id", "invoices.environment_id", "invoices.id"],
            name="fk_pi_payment_requests_invoice_id",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "environment_id"],
            ["environments.tenant_id", "environments.id"],
            name="fk_pi_payment_requests_environment",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_pi_payment_requests_tenant_id_tenants"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_pi_payment_requests")),
        sa.UniqueConstraint("reference", name="uq_pi_payment_requests_reference"),
        sa.UniqueConstraint(
            "tenant_id", "environment_id", "id", name="uq_pi_payment_requests_scope_id"
        ),
        sa.UniqueConstraint(
            "tenant_id", "environment_id", "idempotency_key", name="uq_pi_payment_requests_key"
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("pi_payment_requests")
    op.drop_table("pi_customer_payment_settings")
    # ### end Alembic commands ###
