"""pi campaigns recipients and sending controls

Revision ID: 0010_pi_campaigns
Revises: 0009_pi_customer_payments
"""

import sqlalchemy as sa
from alembic import op

revision = "0010_pi_campaigns"
down_revision = "0009_pi_customer_payments"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "pi_campaign_recipients",
        sa.Column("campaign_id", sa.Uuid(), nullable=False),
        sa.Column("customer_id", sa.Uuid(), nullable=False),
        sa.Column("conversation_id", sa.Uuid(), nullable=True),
        sa.Column("message_id", sa.Uuid(), nullable=True),
        sa.Column("status", sa.String(length=16), server_default="pending", nullable=False),
        sa.Column("error_code", sa.String(length=64), nullable=True),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("environment_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('pending', 'queued', 'sent', 'skipped', 'failed')",
            name=op.f("ck_pi_campaign_recipients_status"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "environment_id", "campaign_id"],
            ["pi_campaigns.tenant_id", "pi_campaigns.environment_id", "pi_campaigns.id"],
            name="fk_pi_campaign_recipients_campaign_id",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "environment_id"],
            ["environments.tenant_id", "environments.id"],
            name="fk_pi_campaign_recipients_environment",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_pi_campaign_recipients_tenant_id_tenants"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_pi_campaign_recipients")),
        sa.UniqueConstraint(
            "tenant_id",
            "environment_id",
            "campaign_id",
            "customer_id",
            name="uq_pi_campaign_recipient",
        ),
        sa.UniqueConstraint(
            "tenant_id", "environment_id", "id", name="uq_pi_campaign_recipients_scope_id"
        ),
    )
    op.create_index(
        "ix_pi_campaign_recipients_pending",
        "pi_campaign_recipients",
        ["campaign_id", "status"],
        unique=False,
    )
    op.add_column(
        "pi_campaigns", sa.Column("daily_limit", sa.Integer(), server_default="200", nullable=False)
    )
    op.add_column(
        "pi_campaigns", sa.Column("quiet_start", sa.Integer(), server_default="21", nullable=False)
    )
    op.add_column(
        "pi_campaigns", sa.Column("quiet_end", sa.Integer(), server_default="9", nullable=False)
    )
    op.add_column(
        "pi_campaigns", sa.Column("started_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.add_column(
        "pi_campaigns", sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True)
    )
    # ### end Alembic commands ###
    # Campaign permissions for existing tenants' system roles (new tenants get them from
    # access/permissions.py). Custom roles are left to their owners.
    grants = {
        "owner": ("pi.campaigns.read", "pi.campaigns.manage"),
        "admin": ("pi.campaigns.read", "pi.campaigns.manage"),
        "manager": ("pi.campaigns.read", "pi.campaigns.manage"),
        "viewer": ("pi.campaigns.read",),
    }
    for key, permissions in grants.items():
        for permission in permissions:
            op.execute(
                sa.text(
                    "INSERT INTO role_permissions (id, tenant_id, role_id, permission) "
                    "SELECT gen_random_uuid(), r.tenant_id, r.id, :permission FROM roles r "
                    "WHERE r.is_system AND r.key = :key ON CONFLICT DO NOTHING"
                ).bindparams(key=key, permission=permission)
            )


def downgrade() -> None:
    op.execute(
        "DELETE FROM role_permissions "
        "WHERE permission IN ('pi.campaigns.read', 'pi.campaigns.manage')"
    )
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("pi_campaigns", "finished_at")
    op.drop_column("pi_campaigns", "started_at")
    op.drop_column("pi_campaigns", "quiet_end")
    op.drop_column("pi_campaigns", "quiet_start")
    op.drop_column("pi_campaigns", "daily_limit")
    op.drop_index("ix_pi_campaign_recipients_pending", table_name="pi_campaign_recipients")
    op.drop_table("pi_campaign_recipients")
    # ### end Alembic commands ###
