"""pi weekly digests

Revision ID: 0011_pi_digests
Revises: 0010_pi_campaigns
"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision = "0011_pi_digests"
down_revision = "0010_pi_campaigns"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "pi_digests",
        sa.Column("period_start", sa.Date(), nullable=False),
        sa.Column("period_end", sa.Date(), nullable=False),
        sa.Column(
            "metrics", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False
        ),
        sa.Column(
            "delivery", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False
        ),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("environment_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "environment_id"],
            ["environments.tenant_id", "environments.id"],
            name="fk_pi_digests_environment",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_pi_digests_tenant_id_tenants"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_pi_digests")),
        sa.UniqueConstraint("tenant_id", "environment_id", "id", name="uq_pi_digests_scope_id"),
        sa.UniqueConstraint(
            "tenant_id", "environment_id", "period_start", name="uq_pi_digest_week"
        ),
    )
    op.add_column(
        "pi_business_accounts",
        sa.Column("digest_email", sa.Boolean(), server_default="false", nullable=False),
    )
    op.add_column(
        "pi_business_accounts",
        sa.Column("suspended_by_workspace", sa.Boolean(), server_default="false", nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("pi_business_accounts", "suspended_by_workspace")
    op.drop_column("pi_business_accounts", "digest_email")
    op.drop_table("pi_digests")
    # ### end Alembic commands ###
