"""pi number pool

Revision ID: 0012_pi_number_pool
Revises: 0011_pi_digests
"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision = "0012_pi_number_pool"
down_revision = "0011_pi_digests"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "pi_platform_state",
        sa.Column("key", sa.String(length=64), nullable=False),
        sa.Column(
            "value", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("key", name=op.f("pk_pi_platform_state")),
    )
    op.create_table(
        "pi_pool_numbers",
        sa.Column("phone_number_id", sa.String(length=32), nullable=False),
        sa.Column("display_phone_number", sa.String(length=32), server_default="", nullable=False),
        sa.Column("business_account_id", sa.String(length=32), server_default="", nullable=False),
        sa.Column("kapso_customer_id", sa.String(length=120), server_default="", nullable=False),
        sa.Column("country", sa.String(length=2), server_default="", nullable=False),
        sa.Column("status", sa.String(length=16), server_default="available", nullable=False),
        sa.Column("quality_rating", sa.String(length=16), nullable=True),
        sa.Column("name_status", sa.String(length=40), server_default="", nullable=False),
        sa.Column("verified_name", sa.String(length=120), server_default="", nullable=False),
        sa.Column("is_coexistence", sa.Boolean(), server_default="false", nullable=False),
        sa.Column(
            "warnings", postgresql.JSONB(astext_type=sa.Text()), server_default="[]", nullable=False
        ),
        sa.Column("webhook_status", sa.String(length=16), server_default="", nullable=False),
        sa.Column("price_label", sa.String(length=80), server_default="", nullable=False),
        sa.Column("notes", sa.String(length=300), server_default="", nullable=False),
        sa.Column("assigned_tenant_id", sa.Uuid(), nullable=True),
        sa.Column("assigned_environment_id", sa.Uuid(), nullable=True),
        sa.Column("assigned_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("offered_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("synced_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('available', 'reserved', 'assigned', 'retired')",
            name=op.f("ck_pi_pool_numbers_status"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_pi_pool_numbers")),
        sa.UniqueConstraint("phone_number_id", name=op.f("uq_pi_pool_numbers_phone_number_id")),
    )
    op.create_index("ix_pi_pool_numbers_status", "pi_pool_numbers", ["status"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_pi_pool_numbers_status", table_name="pi_pool_numbers")
    op.drop_table("pi_pool_numbers")
    op.drop_table("pi_platform_state")
    # ### end Alembic commands ###
