"""workspace_agent

Revision ID: 0013_workspace_agent
Revises: 0012_pi_number_pool
"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision = "0013_workspace_agent"
down_revision = "0012_pi_number_pool"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # Backfill only built-in roles; custom roles remain explicitly opt-in.
    op.execute("""
        INSERT INTO role_permissions (tenant_id, role_id, permission)
        SELECT r.tenant_id, r.id, p.permission FROM roles r
        CROSS JOIN (VALUES ('tasks.read'), ('tasks.write'), ('tasks.manage')) p(permission)
        WHERE r.is_system AND (
            p.permission = 'tasks.read'
            OR (p.permission = 'tasks.write' AND r.key <> 'viewer')
            OR (p.permission = 'tasks.manage' AND r.key IN ('owner', 'admin', 'manager'))
        ) ON CONFLICT (tenant_id, role_id, permission) DO NOTHING
    """)
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "workspace_agent_actions",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("operation", sa.String(length=40), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("required_permissions", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("status", sa.String(length=12), server_default="pending", nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("result", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("environment_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('pending', 'applied', 'cancelled')",
            name=op.f("ck_workspace_agent_actions_status"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "environment_id"],
            ["environments.tenant_id", "environments.id"],
            name="fk_workspace_agent_actions_environment",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_workspace_agent_actions_tenant_id_tenants"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["platform_users.id"],
            name=op.f("fk_workspace_agent_actions_user_id_platform_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_workspace_agent_actions")),
        sa.UniqueConstraint(
            "tenant_id", "environment_id", "id", name="uq_workspace_agent_actions_scope_id"
        ),
    )
    op.create_index(
        "ix_workspace_agent_actions_owner",
        "workspace_agent_actions",
        ["tenant_id", "environment_id", "user_id"],
        unique=False,
    )
    op.create_table(
        "workspace_tasks",
        sa.Column("created_by", sa.Uuid(), nullable=False),
        sa.Column("assignee_id", sa.Uuid(), nullable=True),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), server_default="", nullable=False),
        sa.Column("specialist", sa.String(length=16), server_default="operations", nullable=False),
        sa.Column("status", sa.String(length=16), server_default="todo", nullable=False),
        sa.Column("priority", sa.String(length=8), server_default="normal", nullable=False),
        sa.Column("due_date", sa.Date(), nullable=True),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("environment_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "priority IN ('low', 'normal', 'high')", name=op.f("ck_workspace_tasks_priority")
        ),
        sa.CheckConstraint(
            "specialist IN ('operations', 'hr', 'finance', 'crm')",
            name=op.f("ck_workspace_tasks_specialist"),
        ),
        sa.CheckConstraint(
            "status IN ('todo', 'in_progress', 'done', 'cancelled')",
            name=op.f("ck_workspace_tasks_status"),
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["platform_users.id"],
            name=op.f("fk_workspace_tasks_created_by_platform_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "assignee_id"],
            ["tenant_memberships.tenant_id", "tenant_memberships.id"],
            name="fk_workspace_tasks_assignee",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "environment_id"],
            ["environments.tenant_id", "environments.id"],
            name="fk_workspace_tasks_environment",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_workspace_tasks_tenant_id_tenants"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_workspace_tasks")),
        sa.UniqueConstraint(
            "tenant_id", "environment_id", "id", name="uq_workspace_tasks_scope_id"
        ),
    )
    op.create_index(
        "ix_workspace_tasks_scope_status",
        "workspace_tasks",
        ["tenant_id", "environment_id", "status"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    op.execute(
        "DELETE FROM role_permissions WHERE permission IN ('tasks.read', 'tasks.write', 'tasks.manage')"
    )
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_workspace_tasks_scope_status", table_name="workspace_tasks")
    op.drop_table("workspace_tasks")
    op.drop_index("ix_workspace_agent_actions_owner", table_name="workspace_agent_actions")
    op.drop_table("workspace_agent_actions")
    # ### end Alembic commands ###
