"""pi platform verification

Revision ID: 0014_pi_platform_verification
Revises: 0013_workspace_agent
"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision = "0014_pi_platform_verification"
down_revision = "0013_workspace_agent"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "pi_platform_settings",
        sa.Column("key", sa.String(length=64), nullable=False),
        sa.Column("value_encrypted", sa.Text(), nullable=True),
        sa.Column("value", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("hint", sa.String(length=16), server_default="", nullable=False),
        sa.Column("updated_by_user_id", sa.Uuid(), nullable=True),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("key", name=op.f("pk_pi_platform_settings")),
    )
    op.create_table(
        "pi_business_verifications",
        sa.Column("status", sa.String(length=20), server_default="not_started", nullable=False),
        sa.Column(
            "details", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False
        ),
        sa.Column("submitted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("decided_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("decided_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("decision_note", sa.String(length=500), server_default="", nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('not_started', 'submitted', 'changes_requested', 'approved', 'rejected')",
            name=op.f("ck_pi_business_verifications_status"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_pi_business_verifications_tenant_id_tenants"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_pi_business_verifications")),
        sa.UniqueConstraint("tenant_id", name="uq_pi_business_verifications_tenant"),
    )
    op.create_index(
        "ix_pi_business_verifications_status",
        "pi_business_verifications",
        ["status", "submitted_at"],
        unique=False,
    )
    op.add_column(
        "pi_business_accounts",
        sa.Column(
            "notification_prefs",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
        ),
    )
    op.add_column(
        "pi_business_accounts",
        sa.Column(
            "lifecycle_state",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
        ),
    )
    op.add_column(
        "pi_business_accounts",
        sa.Column("lifecycle_checked_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.add_column(
        "pi_plans",
        sa.Column("visibility", sa.String(length=16), server_default="public", nullable=False),
    )
    op.add_column(
        "pi_pool_numbers", sa.Column("held_until", sa.DateTime(timezone=True), nullable=True)
    )
    op.create_check_constraint(
        op.f("ck_pi_plans_visibility"), "pi_plans", "visibility IN ('public', 'private')"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("ck_pi_plans_visibility"), "pi_plans", type_="check")
    op.drop_column("pi_pool_numbers", "held_until")
    op.drop_column("pi_plans", "visibility")
    op.drop_column("pi_business_accounts", "lifecycle_checked_at")
    op.drop_column("pi_business_accounts", "lifecycle_state")
    op.drop_column("pi_business_accounts", "notification_prefs")
    op.drop_index("ix_pi_business_verifications_status", table_name="pi_business_verifications")
    op.drop_table("pi_business_verifications")
    op.drop_table("pi_platform_settings")
    # ### end Alembic commands ###
