"""integration_business_workflows

Revision ID: 3ad535597720
Revises: 0006_pi_service_conversations
"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision = "3ad535597720"
down_revision = "0006_pi_service_conversations"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "integration_operations",
        sa.Column("connection_id", sa.Uuid(), nullable=False),
        sa.Column("outbox_event_id", sa.Uuid(), nullable=True),
        sa.Column("kind", sa.String(length=20), nullable=False),
        sa.Column("dedupe_key", sa.String(length=200), nullable=False),
        sa.Column("entity_type", sa.String(length=30), nullable=True),
        sa.Column("entity_id", sa.Uuid(), nullable=True),
        sa.Column("status", sa.String(length=20), server_default="pending", nullable=False),
        sa.Column(
            "input", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False
        ),
        sa.Column(
            "output", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False
        ),
        sa.Column("external_id", sa.String(length=255), nullable=True),
        sa.Column("attempts", sa.Integer(), server_default="0", nullable=False),
        sa.Column("last_error", sa.String(length=300), nullable=True),
        sa.Column("next_attempt_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("environment_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "kind IN ('notification','file','checkout')",
            name=op.f("ck_integration_operations_kind"),
        ),
        sa.CheckConstraint(
            "status IN ('pending','running','succeeded','failed','needs_review','cancelled')",
            name=op.f("ck_integration_operations_status"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "environment_id", "connection_id"],
            [
                "integration_connections.tenant_id",
                "integration_connections.environment_id",
                "integration_connections.id",
            ],
            name="fk_integration_operations_connection_id",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "environment_id", "outbox_event_id"],
            ["outbox_events.tenant_id", "outbox_events.environment_id", "outbox_events.id"],
            name="fk_integration_operations_outbox_event_id",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "environment_id"],
            ["environments.tenant_id", "environments.id"],
            name="fk_integration_operations_environment",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_integration_operations_tenant_id_tenants"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_integration_operations")),
        sa.UniqueConstraint(
            "connection_id", "kind", "external_id", name="uq_integration_operations_external"
        ),
        sa.UniqueConstraint(
            "tenant_id", "environment_id", "dedupe_key", name="uq_integration_operations_dedupe"
        ),
        sa.UniqueConstraint(
            "tenant_id", "environment_id", "id", name="uq_integration_operations_scope_id"
        ),
    )
    op.create_index(
        "ix_integration_operations_due",
        "integration_operations",
        ["kind", "status", "next_attempt_at"],
        unique=False,
    )
    op.create_table(
        "integration_workflows",
        sa.Column("connection_id", sa.Uuid(), nullable=False),
        sa.Column("enabled", sa.Boolean(), server_default="false", nullable=False),
        sa.Column(
            "event_types",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="[]",
            nullable=False,
        ),
        sa.Column(
            "recipients",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="[]",
            nullable=False,
        ),
        sa.Column("enabled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("environment_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "environment_id", "connection_id"],
            [
                "integration_connections.tenant_id",
                "integration_connections.environment_id",
                "integration_connections.id",
            ],
            name="fk_integration_workflows_connection_id",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "environment_id"],
            ["environments.tenant_id", "environments.id"],
            name="fk_integration_workflows_environment",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_integration_workflows_tenant_id_tenants"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_integration_workflows")),
        sa.UniqueConstraint("connection_id", name="uq_integration_workflows_connection"),
        sa.UniqueConstraint(
            "tenant_id", "environment_id", "id", name="uq_integration_workflows_scope_id"
        ),
    )
    op.add_column(
        "whatsapp_connections", sa.Column("integration_connection_id", sa.Uuid(), nullable=True)
    )
    op.create_foreign_key(
        "fk_whatsapp_connections_integration_connection_id",
        "whatsapp_connections",
        "integration_connections",
        ["tenant_id", "environment_id", "integration_connection_id"],
        ["tenant_id", "environment_id", "id"],
        ondelete="RESTRICT",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "fk_whatsapp_connections_integration_connection_id",
        "whatsapp_connections",
        type_="foreignkey",
    )
    op.drop_column("whatsapp_connections", "integration_connection_id")
    op.drop_table("integration_workflows")
    op.drop_index("ix_integration_operations_due", table_name="integration_operations")
    op.drop_table("integration_operations")
    # ### end Alembic commands ###
