"""knowledge_embeddings

Revision ID: ea6781564d8a
Revises: 0cb6ac1ccb54
"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision = "ea6781564d8a"
down_revision = "0cb6ac1ccb54"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "knowledge_chunks",
        sa.Column("embedding_values", postgresql.ARRAY(sa.Float()), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("knowledge_chunks", "embedding_values")
    # ### end Alembic commands ###
