import {
  ArrowLeftRight,
  BadgeDollarSign,
  Bell,
  Blocks,
  BookOpen,
  Bot,
  Boxes,
  Building,
  ChartColumn,
  ChartLine,
  Circle,
  CreditCard,
  FileText,
  FolderTree,
  Gauge,
  Hourglass,
  IdCard,
  Inbox,
  Kanban,
  Landmark,
  Layers,
  LayoutDashboard,
  LifeBuoy,
  MapPin,
  MessageCircle,
  Network,
  Package,
  Receipt,
  ScrollText,
  Settings,
  ShieldCheck,
  ShoppingCart,
  SlidersHorizontal,
  Stamp,
  Tags,
  Target,
  TrendingUp,
  Truck,
  UserCog,
  Users,
  Wallet,
  Warehouse,
  Workflow,
  Activity,
  KeyRound,
  Plug,
  RefreshCw,
  Send,
  TriangleAlert,
  type LucideIcon,
} from "lucide-react";

/**
 * Registry icons are names (so the API can describe navigation); this maps them to
 * components. Unknown names fall back to a neutral glyph instead of breaking the shell.
 */
const ICONS: Record<string, LucideIcon> = {
  "arrow-left-right": ArrowLeftRight,
  "badge-dollar-sign": BadgeDollarSign,
  bell: Bell,
  blocks: Blocks,
  "book-open": BookOpen,
  bot: Bot,
  boxes: Boxes,
  "building-2": Building,
  "chart-column": ChartColumn,
  "chart-line": ChartLine,
  "credit-card": CreditCard,
  "file-text": FileText,
  "folder-tree": FolderTree,
  gauge: Gauge,
  hourglass: Hourglass,
  "id-card": IdCard,
  inbox: Inbox,
  kanban: Kanban,
  landmark: Landmark,
  layers: Layers,
  "layout-dashboard": LayoutDashboard,
  "life-buoy": LifeBuoy,
  "map-pin": MapPin,
  "message-circle": MessageCircle,
  network: Network,
  package: Package,
  receipt: Receipt,
  "scroll-text": ScrollText,
  settings: Settings,
  "shield-check": ShieldCheck,
  "shopping-cart": ShoppingCart,
  "sliders-horizontal": SlidersHorizontal,
  stamp: Stamp,
  tags: Tags,
  target: Target,
  "trending-up": TrendingUp,
  truck: Truck,
  "user-cog": UserCog,
  users: Users,
  wallet: Wallet,
  warehouse: Warehouse,
  workflow: Workflow,
  "triangle-alert": TriangleAlert,
  send: Send,
  "refresh-cw": RefreshCw,
  plug: Plug,
  "key-round": KeyRound,
  activity: Activity,
};

export function NavIcon({
  name,
  className,
}: {
  name: string;
  className?: string;
}) {
  const Icon = ICONS[name] ?? Circle;
  return <Icon className={className} aria-hidden="true" />;
}
