"""The fixed PI tool catalog. Agents can only use tools listed here."""

from app.modules.pi.tools import handlers as h
from app.modules.pi.tools.base import ToolSpec

_SPECS = (
    ToolSpec(
        "search_customer",
        "Check whether a phone number belongs to the current customer.",
        h.SearchCustomerInput,
        h.SearchCustomerOutput,
        h.search_customer,
        "customers.read",
    ),
    ToolSpec(
        "get_customer",
        "Read the current customer's profile.",
        h.GetCustomerInput,
        h.CustomerOut,
        h.get_customer,
        "customers.read",
    ),
    ToolSpec(
        "get_customer_orders",
        "List the current customer's recent orders with status and totals.",
        h.CustomerOrdersInput,
        h.CustomerOrdersOutput,
        h.get_customer_orders,
        "orders.read",
        feature="orders",
    ),
    ToolSpec(
        "get_customer_balance",
        "Read the current customer's open invoice balance.",
        h.Empty,
        h.BalanceOutput,
        h.get_customer_balance,
        "billing.read",
    ),
    ToolSpec(
        "search_products",
        "Search approved, active catalog items with catalog prices.",
        h.SearchProductsInput,
        h.SearchProductsOutput,
        h.search_products,
        "catalog.read",
    ),
    ToolSpec(
        "get_product",
        "Read one approved catalog item and its active options.",
        h.GetProductInput,
        h.ProductOut,
        h.get_product,
        "catalog.read",
    ),
    ToolSpec(
        "check_inventory",
        "Read verified available stock for tracked catalog options.",
        h.InventoryInput,
        h.InventoryOutput,
        h.check_inventory,
        "inventory.read",
    ),
    ToolSpec(
        "create_order_draft",
        "Create a draft order for the current customer at catalog prices.",
        h.DraftInput,
        h.OrderOut,
        h.create_order_draft,
        "orders.write",
        mutation=True,
        feature="orders",
    ),
    ToolSpec(
        "calculate_order_total",
        "Price lines from the catalog and workspace tax rate without saving anything.",
        h.DraftInput,
        h.TotalOutput,
        h.calculate_order_total,
        "catalog.read",
        feature="orders",
    ),
    ToolSpec(
        "create_order",
        "Confirm a draft order. Requires the customer's explicit confirmation token.",
        h.OrderIdInput,
        h.OrderOut,
        h.create_order,
        "orders.write",
        mutation=True,
        requires_confirmation=True,
        feature="orders",
    ),
    ToolSpec(
        "get_order",
        "Read one of the current customer's orders.",
        h.OrderIdInput,
        h.OrderOut,
        h.get_order,
        "orders.read",
        feature="orders",
    ),
    ToolSpec(
        "get_invoice",
        "Read one of the current customer's invoices.",
        h.InvoiceIdInput,
        h.InvoiceOut,
        h.get_invoice,
        "billing.read",
    ),
    ToolSpec(
        "get_company_information",
        "Read the company name, currency and approved company information.",
        h.Empty,
        h.CompanyOutput,
        h.get_company_information,
        "pi.read",
    ),
    ToolSpec(
        "create_quote_draft",
        "Create a draft quote for team review at catalog prices.",
        h.DraftInput,
        h.QuoteOut,
        h.create_quote_draft,
        "quotes.write",
        mutation=True,
        feature="quotes",
    ),
    ToolSpec(
        "search_knowledge_base",
        "Full-text search over approved knowledge passages.",
        h.KnowledgeInput,
        h.KnowledgeOutput,
        h.search_knowledge_base,
        "pi.read",
        feature="knowledge",
    ),
    ToolSpec(
        "search_customer_memory",
        "Read remembered facts about the current customer.",
        h.MemoryInput,
        h.MemoryOutput,
        h.search_customer_memory,
        "pi.memory.read",
    ),
    ToolSpec(
        "create_handoff",
        "Hand the conversation to a team member. Stops automated replies.",
        h.HandoffInput,
        h.HandoffOutput,
        h.create_handoff,
        "pi.handoffs.manage",
        mutation=True,
        feature="handoff",
    ),
    ToolSpec(
        "send_whatsapp_message",
        "Queue a reply to the customer for WhatsApp delivery.",
        h.SendInput,
        h.SendOutput,
        h.send_whatsapp_message,
        "pi.inbox.reply",
        mutation=True,
    ),
)

TOOL_CATALOG: dict[str, ToolSpec] = {spec.name: spec for spec in _SPECS}
