"""The fixed PI tool catalog. Agents can only use tools listed here."""

from app.modules.pi.tools import connector_handlers as c
from app.modules.pi.tools import flow_handlers as f
from app.modules.pi.tools import handlers as h
from app.modules.pi.tools import work_handlers as w
from app.modules.pi.tools.base import ToolSpec

_SPECS = (
    ToolSpec(
        "search_customer",
        "Check whether a phone number belongs to the current customer.",
        h.SearchCustomerInput,
        h.SearchCustomerOutput,
        h.search_customer,
        "customers.read",
    ),
    ToolSpec(
        "get_customer",
        "Read the current customer's profile.",
        h.GetCustomerInput,
        h.CustomerOut,
        h.get_customer,
        "customers.read",
    ),
    ToolSpec(
        "get_customer_orders",
        "List the current customer's recent orders with status and totals.",
        h.CustomerOrdersInput,
        h.CustomerOrdersOutput,
        h.get_customer_orders,
        "orders.read",
        feature="orders",
    ),
    ToolSpec(
        "get_customer_balance",
        "Read the current customer's open invoice balance.",
        h.Empty,
        h.BalanceOutput,
        h.get_customer_balance,
        "billing.read",
    ),
    ToolSpec(
        "search_products",
        "Search approved, active catalog items with catalog prices.",
        h.SearchProductsInput,
        h.SearchProductsOutput,
        h.search_products,
        "catalog.read",
    ),
    ToolSpec(
        "get_product",
        "Read one approved catalog item and its active options.",
        h.GetProductInput,
        h.ProductOut,
        h.get_product,
        "catalog.read",
    ),
    ToolSpec(
        "check_inventory",
        "Read verified available stock for tracked catalog options.",
        h.InventoryInput,
        h.InventoryOutput,
        h.check_inventory,
        "inventory.read",
    ),
    ToolSpec(
        "create_order_draft",
        "Create a draft order for the current customer at catalog prices.",
        h.DraftInput,
        h.OrderOut,
        h.create_order_draft,
        "orders.write",
        mutation=True,
        feature="orders",
    ),
    ToolSpec(
        "calculate_order_total",
        "Price lines from the catalog and workspace tax rate without saving anything.",
        h.DraftInput,
        h.TotalOutput,
        h.calculate_order_total,
        "catalog.read",
        feature="orders",
    ),
    ToolSpec(
        "create_order",
        "Confirm a draft order. Requires the customer's explicit confirmation token.",
        h.OrderIdInput,
        h.OrderOut,
        h.create_order,
        "orders.write",
        mutation=True,
        requires_confirmation=True,
        feature="orders",
    ),
    ToolSpec(
        "get_order",
        "Read one of the current customer's orders.",
        h.OrderIdInput,
        h.OrderOut,
        h.get_order,
        "orders.read",
        feature="orders",
    ),
    ToolSpec(
        "get_invoice",
        "Read one of the current customer's invoices.",
        h.InvoiceIdInput,
        h.InvoiceOut,
        h.get_invoice,
        "billing.read",
    ),
    ToolSpec(
        "get_company_information",
        "Read the company name, currency and approved company information.",
        h.Empty,
        h.CompanyOutput,
        h.get_company_information,
        "pi.read",
    ),
    ToolSpec(
        "create_quote_draft",
        "Create a draft quote for team review at catalog prices.",
        h.DraftInput,
        h.QuoteOut,
        h.create_quote_draft,
        "quotes.write",
        mutation=True,
        feature="quotes",
    ),
    ToolSpec(
        "search_knowledge_base",
        "Full-text search over approved knowledge passages.",
        h.KnowledgeInput,
        h.KnowledgeOutput,
        h.search_knowledge_base,
        "pi.read",
        feature="knowledge",
    ),
    ToolSpec(
        "search_customer_memory",
        "Read remembered facts about the current customer.",
        h.MemoryInput,
        h.MemoryOutput,
        h.search_customer_memory,
        "pi.memory.read",
    ),
    ToolSpec(
        "create_handoff",
        "Hand the conversation to a team member. Stops automated replies.",
        h.HandoffInput,
        h.HandoffOutput,
        h.create_handoff,
        "pi.handoffs.manage",
        mutation=True,
        feature="handoff",
    ),
    ToolSpec(
        "send_whatsapp_message",
        "Queue a reply to the customer for WhatsApp delivery.",
        h.SendInput,
        h.SendOutput,
        h.send_whatsapp_message,
        "pi.inbox.reply",
        mutation=True,
    ),
)

_WORK_SPECS = (
    ToolSpec(
        "check_availability",
        "List bookable services and their free times (business timezone).",
        w.AvailabilityInput,
        w.AvailabilityOutput,
        w.check_availability,
        "pi.bookings.read",
    ),
    ToolSpec(
        "create_booking",
        "Book one free time the customer explicitly agreed to. Rechecks availability.",
        w.BookingInput,
        w.BookingOut,
        w.create_booking,
        "pi.bookings.manage",
        mutation=True,
    ),
    ToolSpec(
        "cancel_booking",
        "Cancel one of the current customer's own bookings.",
        w.BookingIdInput,
        w.BookingOut,
        w.cancel_booking,
        "pi.bookings.manage",
        mutation=True,
    ),
    ToolSpec(
        "get_bookings",
        "List the current customer's upcoming bookings.",
        h.Empty,
        w.BookingsOutput,
        w.get_bookings,
        "pi.bookings.read",
    ),
    ToolSpec(
        "create_task",
        "Create a follow-up task for the team about this customer.",
        w.TaskInput,
        w.TaskOut,
        w.create_task,
        "pi.work.manage",
        mutation=True,
    ),
    ToolSpec(
        "create_ticket",
        "Log a support issue for the team with a priority.",
        w.TicketInput,
        w.TicketOut,
        w.create_ticket,
        "pi.work.manage",
        mutation=True,
    ),
    ToolSpec(
        "request_payment",
        "Send payment instructions for the current customer's own open invoice.",
        w.PaymentRequestInput,
        w.PaymentRequestOut,
        w.request_payment,
        "billing.write",
        mutation=True,
    ),
    ToolSpec(
        "get_payment_status",
        "Read the current customer's payment requests and whether they are paid.",
        h.Empty,
        w.PaymentStatusOutput,
        w.get_payment_status,
        "billing.read",
    ),
    ToolSpec(
        "get_project_status",
        "Read customer-visible status of the current customer's projects.",
        h.Empty,
        w.ProjectStatusOutput,
        w.get_project_status,
        "pi.work.read",
    ),
)

# Tools backed by connections the business authorized itself (Google Calendar, Shopify,
# its email provider). Without the connection they refuse or report `connected: false`.
_CONNECTOR_SPECS = (
    ToolSpec(
        "reschedule_booking",
        "Move one of the current customer's bookings to a free time they agreed to.",
        c.RescheduleInput,
        w.BookingOut,
        c.reschedule_booking,
        "pi.bookings.manage",
        mutation=True,
    ),
    ToolSpec(
        "email_booking_confirmation",
        "Email a booking confirmation to the current customer's address on file.",
        c.BookingEmailInput,
        c.BookingEmailOut,
        c.email_booking_confirmation,
        "pi.bookings.manage",
        mutation=True,
    ),
    ToolSpec(
        "get_store_orders",
        "Read the current customer's recent Shopify orders and delivery status.",
        h.Empty,
        c.StoreOrdersOutput,
        c.get_store_orders,
        "orders.read",
    ),
    ToolSpec(
        "send_form",
        "Send the business's WhatsApp form (lead details, booking request or feedback).",
        f.FormInput,
        f.FormOut,
        f.send_form,
        "pi.inbox.reply",
        mutation=True,
    ),
)

TOOL_CATALOG: dict[str, ToolSpec] = {
    spec.name: spec for spec in (*_SPECS, *_WORK_SPECS, *_CONNECTOR_SPECS)
}
